// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// DeleteCustomersCustomerFidPhonesPhoneFidReader is a Reader for the DeleteCustomersCustomerFidPhonesPhoneFid structure.
type DeleteCustomersCustomerFidPhonesPhoneFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCustomersCustomerFidPhonesPhoneFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteCustomersCustomerFidPhonesPhoneFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteCustomersCustomerFidPhonesPhoneFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteCustomersCustomerFidPhonesPhoneFidOK creates a DeleteCustomersCustomerFidPhonesPhoneFidOK with default headers values
func NewDeleteCustomersCustomerFidPhonesPhoneFidOK() *DeleteCustomersCustomerFidPhonesPhoneFidOK {
	return &DeleteCustomersCustomerFidPhonesPhoneFidOK{}
}

/*
DeleteCustomersCustomerFidPhonesPhoneFidOK describes a response with status code 200, with default header values.

Phone removed
*/
type DeleteCustomersCustomerFidPhonesPhoneFidOK struct {
}

// IsSuccess returns true when this delete customers customer fid phones phone fid o k response has a 2xx status code
func (o *DeleteCustomersCustomerFidPhonesPhoneFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete customers customer fid phones phone fid o k response has a 3xx status code
func (o *DeleteCustomersCustomerFidPhonesPhoneFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete customers customer fid phones phone fid o k response has a 4xx status code
func (o *DeleteCustomersCustomerFidPhonesPhoneFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete customers customer fid phones phone fid o k response has a 5xx status code
func (o *DeleteCustomersCustomerFidPhonesPhoneFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete customers customer fid phones phone fid o k response a status code equal to that given
func (o *DeleteCustomersCustomerFidPhonesPhoneFidOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteCustomersCustomerFidPhonesPhoneFidOK) Error() string {
	return fmt.Sprintf("[DELETE /customers/{customerFid}/phones/{phoneFid}][%d] deleteCustomersCustomerFidPhonesPhoneFidOK ", 200)
}

func (o *DeleteCustomersCustomerFidPhonesPhoneFidOK) String() string {
	return fmt.Sprintf("[DELETE /customers/{customerFid}/phones/{phoneFid}][%d] deleteCustomersCustomerFidPhonesPhoneFidOK ", 200)
}

func (o *DeleteCustomersCustomerFidPhonesPhoneFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCustomersCustomerFidPhonesPhoneFidDefault creates a DeleteCustomersCustomerFidPhonesPhoneFidDefault with default headers values
func NewDeleteCustomersCustomerFidPhonesPhoneFidDefault(code int) *DeleteCustomersCustomerFidPhonesPhoneFidDefault {
	return &DeleteCustomersCustomerFidPhonesPhoneFidDefault{
		_statusCode: code,
	}
}

/*
DeleteCustomersCustomerFidPhonesPhoneFidDefault describes a response with status code -1, with default header values.

Error
*/
type DeleteCustomersCustomerFidPhonesPhoneFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the delete customers customer fid phones phone fid default response
func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete customers customer fid phones phone fid default response has a 2xx status code
func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete customers customer fid phones phone fid default response has a 3xx status code
func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete customers customer fid phones phone fid default response has a 4xx status code
func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete customers customer fid phones phone fid default response has a 5xx status code
func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete customers customer fid phones phone fid default response a status code equal to that given
func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) Error() string {
	return fmt.Sprintf("[DELETE /customers/{customerFid}/phones/{phoneFid}][%d] DeleteCustomersCustomerFidPhonesPhoneFid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) String() string {
	return fmt.Sprintf("[DELETE /customers/{customerFid}/phones/{phoneFid}][%d] DeleteCustomersCustomerFidPhonesPhoneFid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *DeleteCustomersCustomerFidPhonesPhoneFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
