// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomersCustomerFidInvoicesInvoiceFidParams creates a new GetCustomersCustomerFidInvoicesInvoiceFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomersCustomerFidInvoicesInvoiceFidParams() *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	return &GetCustomersCustomerFidInvoicesInvoiceFidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomersCustomerFidInvoicesInvoiceFidParamsWithTimeout creates a new GetCustomersCustomerFidInvoicesInvoiceFidParams object
// with the ability to set a timeout on a request.
func NewGetCustomersCustomerFidInvoicesInvoiceFidParamsWithTimeout(timeout time.Duration) *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	return &GetCustomersCustomerFidInvoicesInvoiceFidParams{
		timeout: timeout,
	}
}

// NewGetCustomersCustomerFidInvoicesInvoiceFidParamsWithContext creates a new GetCustomersCustomerFidInvoicesInvoiceFidParams object
// with the ability to set a context for a request.
func NewGetCustomersCustomerFidInvoicesInvoiceFidParamsWithContext(ctx context.Context) *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	return &GetCustomersCustomerFidInvoicesInvoiceFidParams{
		Context: ctx,
	}
}

// NewGetCustomersCustomerFidInvoicesInvoiceFidParamsWithHTTPClient creates a new GetCustomersCustomerFidInvoicesInvoiceFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomersCustomerFidInvoicesInvoiceFidParamsWithHTTPClient(client *http.Client) *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	return &GetCustomersCustomerFidInvoicesInvoiceFidParams{
		HTTPClient: client,
	}
}

/* GetCustomersCustomerFidInvoicesInvoiceFidParams contains all the parameters to send to the API endpoint
   for the get customers customer fid invoices invoice fid operation.

   Typically these are written to a http.Request.
*/
type GetCustomersCustomerFidInvoicesInvoiceFidParams struct {

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	/* InvoiceFid.

	   Invoice Fid to use
	*/
	InvoiceFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get customers customer fid invoices invoice fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) WithDefaults() *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get customers customer fid invoices invoice fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) WithTimeout(timeout time.Duration) *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) WithContext(ctx context.Context) *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) WithHTTPClient(client *http.Client) *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) WithCustomerFid(customerFid string) *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithInvoiceFid adds the invoiceFid to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) WithInvoiceFid(invoiceFid string) *GetCustomersCustomerFidInvoicesInvoiceFidParams {
	o.SetInvoiceFid(invoiceFid)
	return o
}

// SetInvoiceFid adds the invoiceFid to the get customers customer fid invoices invoice fid params
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) SetInvoiceFid(invoiceFid string) {
	o.InvoiceFid = invoiceFid
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomersCustomerFidInvoicesInvoiceFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	// path param invoiceFid
	if err := r.SetPathParam("invoiceFid", o.InvoiceFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
