// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// GetCustomersCustomerFidPhonesReader is a Reader for the GetCustomersCustomerFidPhones structure.
type GetCustomersCustomerFidPhonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersCustomerFidPhonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomersCustomerFidPhonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCustomersCustomerFidPhonesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCustomersCustomerFidPhonesOK creates a GetCustomersCustomerFidPhonesOK with default headers values
func NewGetCustomersCustomerFidPhonesOK() *GetCustomersCustomerFidPhonesOK {
	return &GetCustomersCustomerFidPhonesOK{}
}

/*
GetCustomersCustomerFidPhonesOK describes a response with status code 200, with default header values.

List of phones
*/
type GetCustomersCustomerFidPhonesOK struct {
	Payload *models.Phones
}

// IsSuccess returns true when this get customers customer fid phones o k response has a 2xx status code
func (o *GetCustomersCustomerFidPhonesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customers customer fid phones o k response has a 3xx status code
func (o *GetCustomersCustomerFidPhonesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers customer fid phones o k response has a 4xx status code
func (o *GetCustomersCustomerFidPhonesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers customer fid phones o k response has a 5xx status code
func (o *GetCustomersCustomerFidPhonesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers customer fid phones o k response a status code equal to that given
func (o *GetCustomersCustomerFidPhonesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get customers customer fid phones o k response
func (o *GetCustomersCustomerFidPhonesOK) Code() int {
	return 200
}

func (o *GetCustomersCustomerFidPhonesOK) Error() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/phones][%d] getCustomersCustomerFidPhonesOK  %+v", 200, o.Payload)
}

func (o *GetCustomersCustomerFidPhonesOK) String() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/phones][%d] getCustomersCustomerFidPhonesOK  %+v", 200, o.Payload)
}

func (o *GetCustomersCustomerFidPhonesOK) GetPayload() *models.Phones {
	return o.Payload
}

func (o *GetCustomersCustomerFidPhonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Phones)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomersCustomerFidPhonesDefault creates a GetCustomersCustomerFidPhonesDefault with default headers values
func NewGetCustomersCustomerFidPhonesDefault(code int) *GetCustomersCustomerFidPhonesDefault {
	return &GetCustomersCustomerFidPhonesDefault{
		_statusCode: code,
	}
}

/*
GetCustomersCustomerFidPhonesDefault describes a response with status code -1, with default header values.

Error
*/
type GetCustomersCustomerFidPhonesDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get customers customer fid phones default response has a 2xx status code
func (o *GetCustomersCustomerFidPhonesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get customers customer fid phones default response has a 3xx status code
func (o *GetCustomersCustomerFidPhonesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get customers customer fid phones default response has a 4xx status code
func (o *GetCustomersCustomerFidPhonesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get customers customer fid phones default response has a 5xx status code
func (o *GetCustomersCustomerFidPhonesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get customers customer fid phones default response a status code equal to that given
func (o *GetCustomersCustomerFidPhonesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get customers customer fid phones default response
func (o *GetCustomersCustomerFidPhonesDefault) Code() int {
	return o._statusCode
}

func (o *GetCustomersCustomerFidPhonesDefault) Error() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/phones][%d] GetCustomersCustomerFidPhones default  %+v", o._statusCode, o.Payload)
}

func (o *GetCustomersCustomerFidPhonesDefault) String() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/phones][%d] GetCustomersCustomerFidPhones default  %+v", o._statusCode, o.Payload)
}

func (o *GetCustomersCustomerFidPhonesDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetCustomersCustomerFidPhonesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
