// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomersCustomerFidInteractionsParams creates a new GetCustomersCustomerFidInteractionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomersCustomerFidInteractionsParams() *GetCustomersCustomerFidInteractionsParams {
	return &GetCustomersCustomerFidInteractionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomersCustomerFidInteractionsParamsWithTimeout creates a new GetCustomersCustomerFidInteractionsParams object
// with the ability to set a timeout on a request.
func NewGetCustomersCustomerFidInteractionsParamsWithTimeout(timeout time.Duration) *GetCustomersCustomerFidInteractionsParams {
	return &GetCustomersCustomerFidInteractionsParams{
		timeout: timeout,
	}
}

// NewGetCustomersCustomerFidInteractionsParamsWithContext creates a new GetCustomersCustomerFidInteractionsParams object
// with the ability to set a context for a request.
func NewGetCustomersCustomerFidInteractionsParamsWithContext(ctx context.Context) *GetCustomersCustomerFidInteractionsParams {
	return &GetCustomersCustomerFidInteractionsParams{
		Context: ctx,
	}
}

// NewGetCustomersCustomerFidInteractionsParamsWithHTTPClient creates a new GetCustomersCustomerFidInteractionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomersCustomerFidInteractionsParamsWithHTTPClient(client *http.Client) *GetCustomersCustomerFidInteractionsParams {
	return &GetCustomersCustomerFidInteractionsParams{
		HTTPClient: client,
	}
}

/*
GetCustomersCustomerFidInteractionsParams contains all the parameters to send to the API endpoint

	for the get customers customer fid interactions operation.

	Typically these are written to a http.Request.
*/
type GetCustomersCustomerFidInteractionsParams struct {

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get customers customer fid interactions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersCustomerFidInteractionsParams) WithDefaults() *GetCustomersCustomerFidInteractionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get customers customer fid interactions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersCustomerFidInteractionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get customers customer fid interactions params
func (o *GetCustomersCustomerFidInteractionsParams) WithTimeout(timeout time.Duration) *GetCustomersCustomerFidInteractionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customers customer fid interactions params
func (o *GetCustomersCustomerFidInteractionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customers customer fid interactions params
func (o *GetCustomersCustomerFidInteractionsParams) WithContext(ctx context.Context) *GetCustomersCustomerFidInteractionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customers customer fid interactions params
func (o *GetCustomersCustomerFidInteractionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customers customer fid interactions params
func (o *GetCustomersCustomerFidInteractionsParams) WithHTTPClient(client *http.Client) *GetCustomersCustomerFidInteractionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customers customer fid interactions params
func (o *GetCustomersCustomerFidInteractionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the get customers customer fid interactions params
func (o *GetCustomersCustomerFidInteractionsParams) WithCustomerFid(customerFid string) *GetCustomersCustomerFidInteractionsParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the get customers customer fid interactions params
func (o *GetCustomersCustomerFidInteractionsParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomersCustomerFidInteractionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
