// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// GetCustomersCustomerFidSubscriptionsSubscriptionFidReader is a Reader for the GetCustomersCustomerFidSubscriptionsSubscriptionFid structure.
type GetCustomersCustomerFidSubscriptionsSubscriptionFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCustomersCustomerFidSubscriptionsSubscriptionFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetCustomersCustomerFidSubscriptionsSubscriptionFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCustomersCustomerFidSubscriptionsSubscriptionFidOK creates a GetCustomersCustomerFidSubscriptionsSubscriptionFidOK with default headers values
func NewGetCustomersCustomerFidSubscriptionsSubscriptionFidOK() *GetCustomersCustomerFidSubscriptionsSubscriptionFidOK {
	return &GetCustomersCustomerFidSubscriptionsSubscriptionFidOK{}
}

/*GetCustomersCustomerFidSubscriptionsSubscriptionFidOK handles this case with default header values.

Loaded subscription
*/
type GetCustomersCustomerFidSubscriptionsSubscriptionFidOK struct {
	Payload *models.GetCustomersCustomerFidSubscriptionsSubscriptionFidOKBody
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidOK) Error() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/subscriptions/{subscriptionFid}][%d] getCustomersCustomerFidSubscriptionsSubscriptionFidOK  %+v", 200, o.Payload)
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCustomersCustomerFidSubscriptionsSubscriptionFidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomersCustomerFidSubscriptionsSubscriptionFidDefault creates a GetCustomersCustomerFidSubscriptionsSubscriptionFidDefault with default headers values
func NewGetCustomersCustomerFidSubscriptionsSubscriptionFidDefault(code int) *GetCustomersCustomerFidSubscriptionsSubscriptionFidDefault {
	return &GetCustomersCustomerFidSubscriptionsSubscriptionFidDefault{
		_statusCode: code,
	}
}

/*GetCustomersCustomerFidSubscriptionsSubscriptionFidDefault handles this case with default header values.

Error
*/
type GetCustomersCustomerFidSubscriptionsSubscriptionFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the get customers customer fid subscriptions subscription fid default response
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidDefault) Code() int {
	return o._statusCode
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidDefault) Error() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/subscriptions/{subscriptionFid}][%d] GetCustomersCustomerFidSubscriptionsSubscriptionFid default  %+v", o._statusCode, o.Payload)
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
