// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetCustomersCustomerFidPaymentMethodsPaymentMethodFidReader is a Reader for the GetCustomersCustomerFidPaymentMethodsPaymentMethodFid structure.
type GetCustomersCustomerFidPaymentMethodsPaymentMethodFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK creates a GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK with default headers values
func NewGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK() *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK {
	return &GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK{}
}

/*
GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK describes a response with status code 200, with default header values.

Payment Method Information
*/
type GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK struct {
	Payload *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody
}

// IsSuccess returns true when this get customers customer fid payment methods payment method fid o k response has a 2xx status code
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customers customer fid payment methods payment method fid o k response has a 3xx status code
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers customer fid payment methods payment method fid o k response has a 4xx status code
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers customer fid payment methods payment method fid o k response has a 5xx status code
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers customer fid payment methods payment method fid o k response a status code equal to that given
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) Error() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/paymentMethods/{paymentMethodFid}][%d] getCustomersCustomerFidPaymentMethodsPaymentMethodFidOK  %+v", 200, o.Payload)
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) String() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/paymentMethods/{paymentMethodFid}][%d] getCustomersCustomerFidPaymentMethodsPaymentMethodFidOK  %+v", 200, o.Payload)
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) GetPayload() *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody {
	return o.Payload
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault creates a GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault with default headers values
func NewGetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault(code int) *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault {
	return &GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault{
		_statusCode: code,
	}
}

/*
GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault describes a response with status code -1, with default header values.

Error
*/
type GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the get customers customer fid payment methods payment method fid default response
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get customers customer fid payment methods payment method fid default response has a 2xx status code
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get customers customer fid payment methods payment method fid default response has a 3xx status code
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get customers customer fid payment methods payment method fid default response has a 4xx status code
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get customers customer fid payment methods payment method fid default response has a 5xx status code
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get customers customer fid payment methods payment method fid default response a status code equal to that given
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) Error() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/paymentMethods/{paymentMethodFid}][%d] GetCustomersCustomerFidPaymentMethodsPaymentMethodFid default  %+v", o._statusCode, o.Payload)
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) String() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/paymentMethods/{paymentMethodFid}][%d] GetCustomersCustomerFidPaymentMethodsPaymentMethodFid default  %+v", o._statusCode, o.Payload)
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody get customers customer fid payment methods payment method fid o k body
swagger:model GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody
*/
type GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody struct {
	models.Envelope

	// data
	Data *models.PaymentMethodResponse `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody) UnmarshalJSON(raw []byte) error {
	// GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO0
	var getCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO0

	// GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1
	var dataGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1 struct {
		Data *models.PaymentMethodResponse `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO0)
	var dataGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1 struct {
		Data *models.PaymentMethodResponse `json:"data,omitempty"`
	}

	dataGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1.Data = o.Data

	jsonDataGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1, errGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1 := swag.WriteJSON(dataGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1)
	if errGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1 != nil {
		return nil, errGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get customers customer fid payment methods payment method fid o k body
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomersCustomerFidPaymentMethodsPaymentMethodFidOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getCustomersCustomerFidPaymentMethodsPaymentMethodFidOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get customers customer fid payment methods payment method fid o k body based on the context it is used
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomersCustomerFidPaymentMethodsPaymentMethodFidOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getCustomersCustomerFidPaymentMethodsPaymentMethodFidOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody) UnmarshalBinary(b []byte) error {
	var res GetCustomersCustomerFidPaymentMethodsPaymentMethodFidOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
