// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchReader is a Reader for the GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearch structure.
type GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK creates a GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK with default headers values
func NewGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK() *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK {
	return &GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK{}
}

/*
GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK describes a response with status code 200, with default header values.

Retention Flow State
*/
type GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK struct {
	Payload *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody
}

// IsSuccess returns true when this get customers customer fid subscriptions subscription fid retention flow flow search o k response has a 2xx status code
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customers customer fid subscriptions subscription fid retention flow flow search o k response has a 3xx status code
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers customer fid subscriptions subscription fid retention flow flow search o k response has a 4xx status code
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers customer fid subscriptions subscription fid retention flow flow search o k response has a 5xx status code
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers customer fid subscriptions subscription fid retention flow flow search o k response a status code equal to that given
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get customers customer fid subscriptions subscription fid retention flow flow search o k response
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) Code() int {
	return 200
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) Error() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/{flowSearch}][%d] getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK  %+v", 200, o.Payload)
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) String() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/{flowSearch}][%d] getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK  %+v", 200, o.Payload)
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) GetPayload() *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody {
	return o.Payload
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault creates a GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault with default headers values
func NewGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault(code int) *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault {
	return &GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault{
		_statusCode: code,
	}
}

/*
GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault describes a response with status code -1, with default header values.

Error
*/
type GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this get customers customer fid subscriptions subscription fid retention flow flow search default response has a 2xx status code
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get customers customer fid subscriptions subscription fid retention flow flow search default response has a 3xx status code
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get customers customer fid subscriptions subscription fid retention flow flow search default response has a 4xx status code
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get customers customer fid subscriptions subscription fid retention flow flow search default response has a 5xx status code
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get customers customer fid subscriptions subscription fid retention flow flow search default response a status code equal to that given
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get customers customer fid subscriptions subscription fid retention flow flow search default response
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) Code() int {
	return o._statusCode
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) Error() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/{flowSearch}][%d] GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearch default  %+v", o._statusCode, o.Payload)
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) String() string {
	return fmt.Sprintf("[GET /customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/{flowSearch}][%d] GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearch default  %+v", o._statusCode, o.Payload)
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody get customers customer fid subscriptions subscription fid retention flow flow search o k body
swagger:model GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody
*/
type GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody struct {
	models.Envelope

	// data
	Data *models.RetentionFlowState `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody) UnmarshalJSON(raw []byte) error {
	// GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO0
	var getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO0

	// GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1
	var dataGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1 struct {
		Data *models.RetentionFlowState `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO0)
	var dataGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1 struct {
		Data *models.RetentionFlowState `json:"data,omitempty"`
	}

	dataGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1.Data = o.Data

	jsonDataGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1, errGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1 := swag.WriteJSON(dataGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1)
	if errGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1 != nil {
		return nil, errGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get customers customer fid subscriptions subscription fid retention flow flow search o k body
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get customers customer fid subscriptions subscription fid retention flow flow search o k body based on the context it is used
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody) UnmarshalBinary(b []byte) error {
	var res GetCustomersCustomerFidSubscriptionsSubscriptionFidRetentionFlowFlowSearchOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
