// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams creates a new GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams() *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	return &GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParamsWithTimeout creates a new GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams object
// with the ability to set a timeout on a request.
func NewGetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParamsWithTimeout(timeout time.Duration) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	return &GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams{
		timeout: timeout,
	}
}

// NewGetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParamsWithContext creates a new GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams object
// with the ability to set a context for a request.
func NewGetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParamsWithContext(ctx context.Context) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	return &GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams{
		Context: ctx,
	}
}

// NewGetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParamsWithHTTPClient creates a new GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParamsWithHTTPClient(client *http.Client) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	return &GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams{
		HTTPClient: client,
	}
}

/*
GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams contains all the parameters to send to the API endpoint

	for the get customers customer fid subscriptions subscription fid cancel flow flow search options operation.

	Typically these are written to a http.Request.
*/
type GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams struct {

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	/* FlowSearch.

	   The unique code or fid for the flow you wish to retrieve
	*/
	FlowSearch string

	/* SubscriptionFid.

	   Subscription FID to use
	*/
	SubscriptionFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get customers customer fid subscriptions subscription fid cancel flow flow search options params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) WithDefaults() *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get customers customer fid subscriptions subscription fid cancel flow flow search options params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) WithTimeout(timeout time.Duration) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) WithContext(ctx context.Context) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) WithHTTPClient(client *http.Client) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) WithCustomerFid(customerFid string) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithFlowSearch adds the flowSearch to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) WithFlowSearch(flowSearch string) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	o.SetFlowSearch(flowSearch)
	return o
}

// SetFlowSearch adds the flowSearch to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) SetFlowSearch(flowSearch string) {
	o.FlowSearch = flowSearch
}

// WithSubscriptionFid adds the subscriptionFid to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) WithSubscriptionFid(subscriptionFid string) *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams {
	o.SetSubscriptionFid(subscriptionFid)
	return o
}

// SetSubscriptionFid adds the subscriptionFid to the get customers customer fid subscriptions subscription fid cancel flow flow search options params
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) SetSubscriptionFid(subscriptionFid string) {
	o.SubscriptionFid = subscriptionFid
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomersCustomerFidSubscriptionsSubscriptionFidCancelFlowFlowSearchOptionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	// path param flowSearch
	if err := r.SetPathParam("flowSearch", o.FlowSearch); err != nil {
		return err
	}

	// path param subscriptionFid
	if err := r.SetPathParam("subscriptionFid", o.SubscriptionFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
