// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PostCustomersCustomerFidEmailsReader is a Reader for the PostCustomersCustomerFidEmails structure.
type PostCustomersCustomerFidEmailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersCustomerFidEmailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostCustomersCustomerFidEmailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostCustomersCustomerFidEmailsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCustomersCustomerFidEmailsOK creates a PostCustomersCustomerFidEmailsOK with default headers values
func NewPostCustomersCustomerFidEmailsOK() *PostCustomersCustomerFidEmailsOK {
	return &PostCustomersCustomerFidEmailsOK{}
}

/*
PostCustomersCustomerFidEmailsOK describes a response with status code 200, with default header values.

Email Added
*/
type PostCustomersCustomerFidEmailsOK struct {
}

// IsSuccess returns true when this post customers customer fid emails o k response has a 2xx status code
func (o *PostCustomersCustomerFidEmailsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post customers customer fid emails o k response has a 3xx status code
func (o *PostCustomersCustomerFidEmailsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers customer fid emails o k response has a 4xx status code
func (o *PostCustomersCustomerFidEmailsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers customer fid emails o k response has a 5xx status code
func (o *PostCustomersCustomerFidEmailsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers customer fid emails o k response a status code equal to that given
func (o *PostCustomersCustomerFidEmailsOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostCustomersCustomerFidEmailsOK) Error() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/emails][%d] postCustomersCustomerFidEmailsOK ", 200)
}

func (o *PostCustomersCustomerFidEmailsOK) String() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/emails][%d] postCustomersCustomerFidEmailsOK ", 200)
}

func (o *PostCustomersCustomerFidEmailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomersCustomerFidEmailsDefault creates a PostCustomersCustomerFidEmailsDefault with default headers values
func NewPostCustomersCustomerFidEmailsDefault(code int) *PostCustomersCustomerFidEmailsDefault {
	return &PostCustomersCustomerFidEmailsDefault{
		_statusCode: code,
	}
}

/*
PostCustomersCustomerFidEmailsDefault describes a response with status code -1, with default header values.

Error
*/
type PostCustomersCustomerFidEmailsDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the post customers customer fid emails default response
func (o *PostCustomersCustomerFidEmailsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this post customers customer fid emails default response has a 2xx status code
func (o *PostCustomersCustomerFidEmailsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post customers customer fid emails default response has a 3xx status code
func (o *PostCustomersCustomerFidEmailsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post customers customer fid emails default response has a 4xx status code
func (o *PostCustomersCustomerFidEmailsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post customers customer fid emails default response has a 5xx status code
func (o *PostCustomersCustomerFidEmailsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post customers customer fid emails default response a status code equal to that given
func (o *PostCustomersCustomerFidEmailsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PostCustomersCustomerFidEmailsDefault) Error() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/emails][%d] PostCustomersCustomerFidEmails default  %+v", o._statusCode, o.Payload)
}

func (o *PostCustomersCustomerFidEmailsDefault) String() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/emails][%d] PostCustomersCustomerFidEmails default  %+v", o._statusCode, o.Payload)
}

func (o *PostCustomersCustomerFidEmailsDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PostCustomersCustomerFidEmailsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
