// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// PostCustomersCustomerFidInteractionsReader is a Reader for the PostCustomersCustomerFidInteractions structure.
type PostCustomersCustomerFidInteractionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersCustomerFidInteractionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostCustomersCustomerFidInteractionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostCustomersCustomerFidInteractionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCustomersCustomerFidInteractionsOK creates a PostCustomersCustomerFidInteractionsOK with default headers values
func NewPostCustomersCustomerFidInteractionsOK() *PostCustomersCustomerFidInteractionsOK {
	return &PostCustomersCustomerFidInteractionsOK{}
}

/*PostCustomersCustomerFidInteractionsOK handles this case with default header values.

Create Interaction Response
*/
type PostCustomersCustomerFidInteractionsOK struct {
	Payload *PostCustomersCustomerFidInteractionsOKBody
}

func (o *PostCustomersCustomerFidInteractionsOK) Error() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/interactions][%d] postCustomersCustomerFidInteractionsOK  %+v", 200, o.Payload)
}

func (o *PostCustomersCustomerFidInteractionsOK) GetPayload() *PostCustomersCustomerFidInteractionsOKBody {
	return o.Payload
}

func (o *PostCustomersCustomerFidInteractionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostCustomersCustomerFidInteractionsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCustomersCustomerFidInteractionsDefault creates a PostCustomersCustomerFidInteractionsDefault with default headers values
func NewPostCustomersCustomerFidInteractionsDefault(code int) *PostCustomersCustomerFidInteractionsDefault {
	return &PostCustomersCustomerFidInteractionsDefault{
		_statusCode: code,
	}
}

/*PostCustomersCustomerFidInteractionsDefault handles this case with default header values.

Error
*/
type PostCustomersCustomerFidInteractionsDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the post customers customer fid interactions default response
func (o *PostCustomersCustomerFidInteractionsDefault) Code() int {
	return o._statusCode
}

func (o *PostCustomersCustomerFidInteractionsDefault) Error() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/interactions][%d] PostCustomersCustomerFidInteractions default  %+v", o._statusCode, o.Payload)
}

func (o *PostCustomersCustomerFidInteractionsDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PostCustomersCustomerFidInteractionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostCustomersCustomerFidInteractionsOKBody post customers customer fid interactions o k body
swagger:model PostCustomersCustomerFidInteractionsOKBody
*/
type PostCustomersCustomerFidInteractionsOKBody struct {
	models.Envelope

	// data
	Data *models.CreateInteraction `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostCustomersCustomerFidInteractionsOKBody) UnmarshalJSON(raw []byte) error {
	// PostCustomersCustomerFidInteractionsOKBodyAO0
	var postCustomersCustomerFidInteractionsOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &postCustomersCustomerFidInteractionsOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = postCustomersCustomerFidInteractionsOKBodyAO0

	// PostCustomersCustomerFidInteractionsOKBodyAO1
	var dataPostCustomersCustomerFidInteractionsOKBodyAO1 struct {
		Data *models.CreateInteraction `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPostCustomersCustomerFidInteractionsOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataPostCustomersCustomerFidInteractionsOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostCustomersCustomerFidInteractionsOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	postCustomersCustomerFidInteractionsOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postCustomersCustomerFidInteractionsOKBodyAO0)
	var dataPostCustomersCustomerFidInteractionsOKBodyAO1 struct {
		Data *models.CreateInteraction `json:"data,omitempty"`
	}

	dataPostCustomersCustomerFidInteractionsOKBodyAO1.Data = o.Data

	jsonDataPostCustomersCustomerFidInteractionsOKBodyAO1, errPostCustomersCustomerFidInteractionsOKBodyAO1 := swag.WriteJSON(dataPostCustomersCustomerFidInteractionsOKBodyAO1)
	if errPostCustomersCustomerFidInteractionsOKBodyAO1 != nil {
		return nil, errPostCustomersCustomerFidInteractionsOKBodyAO1
	}
	_parts = append(_parts, jsonDataPostCustomersCustomerFidInteractionsOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post customers customer fid interactions o k body
func (o *PostCustomersCustomerFidInteractionsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCustomersCustomerFidInteractionsOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postCustomersCustomerFidInteractionsOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostCustomersCustomerFidInteractionsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCustomersCustomerFidInteractionsOKBody) UnmarshalBinary(b []byte) error {
	var res PostCustomersCustomerFidInteractionsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
