// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyReader is a Reader for the PutCustomersCustomerFidSubscriptionsSubscriptionFidModify structure.
type PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK creates a PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK with default headers values
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK() *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK{}
}

/*PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK handles this case with default header values.

Created new open order
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK struct {
	Payload *models.Order
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK) Error() string {
	return fmt.Sprintf("[PUT /customers/{customerFid}/subscriptions/{subscriptionFid}/modify][%d] putCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK  %+v", 200, o.Payload)
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Order)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest creates a PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest with default headers values
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest() *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest{}
}

/*PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest handles this case with default header values.

Invalid payload data
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest struct {
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest) Error() string {
	return fmt.Sprintf("[PUT /customers/{customerFid}/subscriptions/{subscriptionFid}/modify][%d] putCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest ", 400)
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound creates a PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound with default headers values
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound() *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound{}
}

/*PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound handles this case with default header values.

Subscription not found
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound struct {
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound) Error() string {
	return fmt.Sprintf("[PUT /customers/{customerFid}/subscriptions/{subscriptionFid}/modify][%d] putCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound ", 404)
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
