// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutCustomersCustomerFidContactsContactFidParams creates a new PutCustomersCustomerFidContactsContactFidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutCustomersCustomerFidContactsContactFidParams() *PutCustomersCustomerFidContactsContactFidParams {
	return &PutCustomersCustomerFidContactsContactFidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutCustomersCustomerFidContactsContactFidParamsWithTimeout creates a new PutCustomersCustomerFidContactsContactFidParams object
// with the ability to set a timeout on a request.
func NewPutCustomersCustomerFidContactsContactFidParamsWithTimeout(timeout time.Duration) *PutCustomersCustomerFidContactsContactFidParams {
	return &PutCustomersCustomerFidContactsContactFidParams{
		timeout: timeout,
	}
}

// NewPutCustomersCustomerFidContactsContactFidParamsWithContext creates a new PutCustomersCustomerFidContactsContactFidParams object
// with the ability to set a context for a request.
func NewPutCustomersCustomerFidContactsContactFidParamsWithContext(ctx context.Context) *PutCustomersCustomerFidContactsContactFidParams {
	return &PutCustomersCustomerFidContactsContactFidParams{
		Context: ctx,
	}
}

// NewPutCustomersCustomerFidContactsContactFidParamsWithHTTPClient creates a new PutCustomersCustomerFidContactsContactFidParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutCustomersCustomerFidContactsContactFidParamsWithHTTPClient(client *http.Client) *PutCustomersCustomerFidContactsContactFidParams {
	return &PutCustomersCustomerFidContactsContactFidParams{
		HTTPClient: client,
	}
}

/*
PutCustomersCustomerFidContactsContactFidParams contains all the parameters to send to the API endpoint

	for the put customers customer fid contacts contact fid operation.

	Typically these are written to a http.Request.
*/
type PutCustomersCustomerFidContactsContactFidParams struct {

	/* Birthday.

	   Birthday
	*/
	Birthday *string

	/* ContactFid.

	   Contact FID to use
	*/
	ContactFid string

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	/* DefaultAddressFid.

	   Default Address FID
	*/
	DefaultAddressFid *string

	/* DefaultEmailFid.

	   Default Email FID
	*/
	DefaultEmailFid *string

	/* DefaultPhoneFid.

	   Default Phone FID
	*/
	DefaultPhoneFid *string

	/* ExternalReference.

	   External Reference
	*/
	ExternalReference *string

	/* FirstName.

	   First Name
	*/
	FirstName *string

	/* JobTitle.

	   Job Title
	*/
	JobTitle *string

	/* LastName.

	   Last Name
	*/
	LastName *string

	/* MiddleNames.

	   Middle Names
	*/
	MiddleNames *string

	/* Nickname.

	   Nickname
	*/
	Nickname *string

	/* Prefix.

	   Prefix
	*/
	Prefix *string

	/* Suffix.

	   Suffix
	*/
	Suffix *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put customers customer fid contacts contact fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCustomersCustomerFidContactsContactFidParams) WithDefaults() *PutCustomersCustomerFidContactsContactFidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put customers customer fid contacts contact fid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCustomersCustomerFidContactsContactFidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithTimeout(timeout time.Duration) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithContext(ctx context.Context) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithHTTPClient(client *http.Client) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBirthday adds the birthday to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithBirthday(birthday *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetBirthday(birthday)
	return o
}

// SetBirthday adds the birthday to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetBirthday(birthday *string) {
	o.Birthday = birthday
}

// WithContactFid adds the contactFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithContactFid(contactFid string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetContactFid(contactFid)
	return o
}

// SetContactFid adds the contactFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetContactFid(contactFid string) {
	o.ContactFid = contactFid
}

// WithCustomerFid adds the customerFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithCustomerFid(customerFid string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithDefaultAddressFid adds the defaultAddressFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithDefaultAddressFid(defaultAddressFid *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetDefaultAddressFid(defaultAddressFid)
	return o
}

// SetDefaultAddressFid adds the defaultAddressFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetDefaultAddressFid(defaultAddressFid *string) {
	o.DefaultAddressFid = defaultAddressFid
}

// WithDefaultEmailFid adds the defaultEmailFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithDefaultEmailFid(defaultEmailFid *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetDefaultEmailFid(defaultEmailFid)
	return o
}

// SetDefaultEmailFid adds the defaultEmailFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetDefaultEmailFid(defaultEmailFid *string) {
	o.DefaultEmailFid = defaultEmailFid
}

// WithDefaultPhoneFid adds the defaultPhoneFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithDefaultPhoneFid(defaultPhoneFid *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetDefaultPhoneFid(defaultPhoneFid)
	return o
}

// SetDefaultPhoneFid adds the defaultPhoneFid to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetDefaultPhoneFid(defaultPhoneFid *string) {
	o.DefaultPhoneFid = defaultPhoneFid
}

// WithExternalReference adds the externalReference to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithExternalReference(externalReference *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetExternalReference(externalReference)
	return o
}

// SetExternalReference adds the externalReference to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetExternalReference(externalReference *string) {
	o.ExternalReference = externalReference
}

// WithFirstName adds the firstName to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithFirstName(firstName *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetFirstName(firstName)
	return o
}

// SetFirstName adds the firstName to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetFirstName(firstName *string) {
	o.FirstName = firstName
}

// WithJobTitle adds the jobTitle to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithJobTitle(jobTitle *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetJobTitle(jobTitle)
	return o
}

// SetJobTitle adds the jobTitle to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetJobTitle(jobTitle *string) {
	o.JobTitle = jobTitle
}

// WithLastName adds the lastName to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithLastName(lastName *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetLastName(lastName)
	return o
}

// SetLastName adds the lastName to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetLastName(lastName *string) {
	o.LastName = lastName
}

// WithMiddleNames adds the middleNames to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithMiddleNames(middleNames *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetMiddleNames(middleNames)
	return o
}

// SetMiddleNames adds the middleNames to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetMiddleNames(middleNames *string) {
	o.MiddleNames = middleNames
}

// WithNickname adds the nickname to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithNickname(nickname *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetNickname(nickname)
	return o
}

// SetNickname adds the nickname to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetNickname(nickname *string) {
	o.Nickname = nickname
}

// WithPrefix adds the prefix to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithPrefix(prefix *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetPrefix(prefix)
	return o
}

// SetPrefix adds the prefix to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetPrefix(prefix *string) {
	o.Prefix = prefix
}

// WithSuffix adds the suffix to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) WithSuffix(suffix *string) *PutCustomersCustomerFidContactsContactFidParams {
	o.SetSuffix(suffix)
	return o
}

// SetSuffix adds the suffix to the put customers customer fid contacts contact fid params
func (o *PutCustomersCustomerFidContactsContactFidParams) SetSuffix(suffix *string) {
	o.Suffix = suffix
}

// WriteToRequest writes these params to a swagger request
func (o *PutCustomersCustomerFidContactsContactFidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Birthday != nil {

		// form param birthday
		var frBirthday string
		if o.Birthday != nil {
			frBirthday = *o.Birthday
		}
		fBirthday := frBirthday
		if fBirthday != "" {
			if err := r.SetFormParam("birthday", fBirthday); err != nil {
				return err
			}
		}
	}

	// path param contactFid
	if err := r.SetPathParam("contactFid", o.ContactFid); err != nil {
		return err
	}

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	if o.DefaultAddressFid != nil {

		// form param defaultAddressFid
		var frDefaultAddressFid string
		if o.DefaultAddressFid != nil {
			frDefaultAddressFid = *o.DefaultAddressFid
		}
		fDefaultAddressFid := frDefaultAddressFid
		if fDefaultAddressFid != "" {
			if err := r.SetFormParam("defaultAddressFid", fDefaultAddressFid); err != nil {
				return err
			}
		}
	}

	if o.DefaultEmailFid != nil {

		// form param defaultEmailFid
		var frDefaultEmailFid string
		if o.DefaultEmailFid != nil {
			frDefaultEmailFid = *o.DefaultEmailFid
		}
		fDefaultEmailFid := frDefaultEmailFid
		if fDefaultEmailFid != "" {
			if err := r.SetFormParam("defaultEmailFid", fDefaultEmailFid); err != nil {
				return err
			}
		}
	}

	if o.DefaultPhoneFid != nil {

		// form param defaultPhoneFid
		var frDefaultPhoneFid string
		if o.DefaultPhoneFid != nil {
			frDefaultPhoneFid = *o.DefaultPhoneFid
		}
		fDefaultPhoneFid := frDefaultPhoneFid
		if fDefaultPhoneFid != "" {
			if err := r.SetFormParam("defaultPhoneFid", fDefaultPhoneFid); err != nil {
				return err
			}
		}
	}

	if o.ExternalReference != nil {

		// form param externalReference
		var frExternalReference string
		if o.ExternalReference != nil {
			frExternalReference = *o.ExternalReference
		}
		fExternalReference := frExternalReference
		if fExternalReference != "" {
			if err := r.SetFormParam("externalReference", fExternalReference); err != nil {
				return err
			}
		}
	}

	if o.FirstName != nil {

		// form param firstName
		var frFirstName string
		if o.FirstName != nil {
			frFirstName = *o.FirstName
		}
		fFirstName := frFirstName
		if fFirstName != "" {
			if err := r.SetFormParam("firstName", fFirstName); err != nil {
				return err
			}
		}
	}

	if o.JobTitle != nil {

		// form param jobTitle
		var frJobTitle string
		if o.JobTitle != nil {
			frJobTitle = *o.JobTitle
		}
		fJobTitle := frJobTitle
		if fJobTitle != "" {
			if err := r.SetFormParam("jobTitle", fJobTitle); err != nil {
				return err
			}
		}
	}

	if o.LastName != nil {

		// form param lastName
		var frLastName string
		if o.LastName != nil {
			frLastName = *o.LastName
		}
		fLastName := frLastName
		if fLastName != "" {
			if err := r.SetFormParam("lastName", fLastName); err != nil {
				return err
			}
		}
	}

	if o.MiddleNames != nil {

		// form param middleNames
		var frMiddleNames string
		if o.MiddleNames != nil {
			frMiddleNames = *o.MiddleNames
		}
		fMiddleNames := frMiddleNames
		if fMiddleNames != "" {
			if err := r.SetFormParam("middleNames", fMiddleNames); err != nil {
				return err
			}
		}
	}

	if o.Nickname != nil {

		// form param nickname
		var frNickname string
		if o.Nickname != nil {
			frNickname = *o.Nickname
		}
		fNickname := frNickname
		if fNickname != "" {
			if err := r.SetFormParam("nickname", fNickname); err != nil {
				return err
			}
		}
	}

	if o.Prefix != nil {

		// form param prefix
		var frPrefix string
		if o.Prefix != nil {
			frPrefix = *o.Prefix
		}
		fPrefix := frPrefix
		if fPrefix != "" {
			if err := r.SetFormParam("prefix", fPrefix); err != nil {
				return err
			}
		}
	}

	if o.Suffix != nil {

		// form param suffix
		var frSuffix string
		if o.Suffix != nil {
			frSuffix = *o.Suffix
		}
		fSuffix := frSuffix
		if fSuffix != "" {
			if err := r.SetFormParam("suffix", fSuffix); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
