// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams() *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParamsWithTimeout creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams object
// with the ability to set a timeout on a request.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParamsWithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams{
		timeout: timeout,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParamsWithContext creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams object
// with the ability to set a context for a request.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParamsWithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams{
		Context: ctx,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParamsWithHTTPClient creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParamsWithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams{
		HTTPClient: client,
	}
}

/*
PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams contains all the parameters to send to the API endpoint

	for the put customers customer fid subscriptions subscription fid reactivate operation.

	Typically these are written to a http.Request.
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams struct {

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	/* SubscriptionFid.

	   Subscription FID to use
	*/
	SubscriptionFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put customers customer fid subscriptions subscription fid reactivate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) WithDefaults() *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put customers customer fid subscriptions subscription fid reactivate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) WithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) WithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) WithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) WithCustomerFid(customerFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithSubscriptionFid adds the subscriptionFid to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) WithSubscriptionFid(subscriptionFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams {
	o.SetSubscriptionFid(subscriptionFid)
	return o
}

// SetSubscriptionFid adds the subscriptionFid to the put customers customer fid subscriptions subscription fid reactivate params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) SetSubscriptionFid(subscriptionFid string) {
	o.SubscriptionFid = subscriptionFid
}

// WriteToRequest writes these params to a swagger request
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReactivateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	// path param subscriptionFid
	if err := r.SetPathParam("subscriptionFid", o.SubscriptionFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
