// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PutCustomersCustomerFidSubscriptionsSubscriptionFidReader is a Reader for the PutCustomersCustomerFidSubscriptionsSubscriptionFid structure.
type PutCustomersCustomerFidSubscriptionsSubscriptionFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutCustomersCustomerFidSubscriptionsSubscriptionFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutCustomersCustomerFidSubscriptionsSubscriptionFidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidOK creates a PutCustomersCustomerFidSubscriptionsSubscriptionFidOK with default headers values
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidOK() *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidOK{}
}

/*
PutCustomersCustomerFidSubscriptionsSubscriptionFidOK describes a response with status code 200, with default header values.

Subscription Updated
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidOK struct {
}

// IsSuccess returns true when this put customers customer fid subscriptions subscription fid o k response has a 2xx status code
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put customers customer fid subscriptions subscription fid o k response has a 3xx status code
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put customers customer fid subscriptions subscription fid o k response has a 4xx status code
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put customers customer fid subscriptions subscription fid o k response has a 5xx status code
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put customers customer fid subscriptions subscription fid o k response a status code equal to that given
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put customers customer fid subscriptions subscription fid o k response
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) Code() int {
	return 200
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) Error() string {
	return fmt.Sprintf("[PUT /customers/{customerFid}/subscriptions/{subscriptionFid}][%d] putCustomersCustomerFidSubscriptionsSubscriptionFidOK ", 200)
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) String() string {
	return fmt.Sprintf("[PUT /customers/{customerFid}/subscriptions/{subscriptionFid}][%d] putCustomersCustomerFidSubscriptionsSubscriptionFidOK ", 200)
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidDefault creates a PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault with default headers values
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidDefault(code int) *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault{
		_statusCode: code,
	}
}

/*
PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault describes a response with status code -1, with default header values.

Error
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this put customers customer fid subscriptions subscription fid default response has a 2xx status code
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put customers customer fid subscriptions subscription fid default response has a 3xx status code
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put customers customer fid subscriptions subscription fid default response has a 4xx status code
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put customers customer fid subscriptions subscription fid default response has a 5xx status code
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put customers customer fid subscriptions subscription fid default response a status code equal to that given
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put customers customer fid subscriptions subscription fid default response
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) Code() int {
	return o._statusCode
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) Error() string {
	return fmt.Sprintf("[PUT /customers/{customerFid}/subscriptions/{subscriptionFid}][%d] PutCustomersCustomerFidSubscriptionsSubscriptionFid default  %+v", o._statusCode, o.Payload)
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) String() string {
	return fmt.Sprintf("[PUT /customers/{customerFid}/subscriptions/{subscriptionFid}][%d] PutCustomersCustomerFidSubscriptionsSubscriptionFid default  %+v", o._statusCode, o.Payload)
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
