// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutCustomersCustomerFidLifecycleStageParams creates a new PutCustomersCustomerFidLifecycleStageParams object
// with the default values initialized.
func NewPutCustomersCustomerFidLifecycleStageParams() *PutCustomersCustomerFidLifecycleStageParams {
	var ()
	return &PutCustomersCustomerFidLifecycleStageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCustomersCustomerFidLifecycleStageParamsWithTimeout creates a new PutCustomersCustomerFidLifecycleStageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCustomersCustomerFidLifecycleStageParamsWithTimeout(timeout time.Duration) *PutCustomersCustomerFidLifecycleStageParams {
	var ()
	return &PutCustomersCustomerFidLifecycleStageParams{

		timeout: timeout,
	}
}

// NewPutCustomersCustomerFidLifecycleStageParamsWithContext creates a new PutCustomersCustomerFidLifecycleStageParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCustomersCustomerFidLifecycleStageParamsWithContext(ctx context.Context) *PutCustomersCustomerFidLifecycleStageParams {
	var ()
	return &PutCustomersCustomerFidLifecycleStageParams{

		Context: ctx,
	}
}

// NewPutCustomersCustomerFidLifecycleStageParamsWithHTTPClient creates a new PutCustomersCustomerFidLifecycleStageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCustomersCustomerFidLifecycleStageParamsWithHTTPClient(client *http.Client) *PutCustomersCustomerFidLifecycleStageParams {
	var ()
	return &PutCustomersCustomerFidLifecycleStageParams{
		HTTPClient: client,
	}
}

/*PutCustomersCustomerFidLifecycleStageParams contains all the parameters to send to the API endpoint
for the put customers customer fid lifecycle stage operation typically these are written to a http.Request
*/
type PutCustomersCustomerFidLifecycleStageParams struct {

	/*CustomerFid
	  Customer FID to use

	*/
	CustomerFid string
	/*CustomerLifecycle*/
	CustomerLifecycle string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) WithTimeout(timeout time.Duration) *PutCustomersCustomerFidLifecycleStageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) WithContext(ctx context.Context) *PutCustomersCustomerFidLifecycleStageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) WithHTTPClient(client *http.Client) *PutCustomersCustomerFidLifecycleStageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) WithCustomerFid(customerFid string) *PutCustomersCustomerFidLifecycleStageParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithCustomerLifecycle adds the customerLifecycle to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) WithCustomerLifecycle(customerLifecycle string) *PutCustomersCustomerFidLifecycleStageParams {
	o.SetCustomerLifecycle(customerLifecycle)
	return o
}

// SetCustomerLifecycle adds the customerLifecycle to the put customers customer fid lifecycle stage params
func (o *PutCustomersCustomerFidLifecycleStageParams) SetCustomerLifecycle(customerLifecycle string) {
	o.CustomerLifecycle = customerLifecycle
}

// WriteToRequest writes these params to a swagger request
func (o *PutCustomersCustomerFidLifecycleStageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	// form param customerLifecycle
	frCustomerLifecycle := o.CustomerLifecycle
	fCustomerLifecycle := frCustomerLifecycle
	if fCustomerLifecycle != "" {
		if err := r.SetFormParam("customerLifecycle", fCustomerLifecycle); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
