// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams object
// with the default values initialized.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams() *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	var ()
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParamsWithTimeout creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParamsWithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	var ()
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams{

		timeout: timeout,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParamsWithContext creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParamsWithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	var ()
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams{

		Context: ctx,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParamsWithHTTPClient creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParamsWithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	var ()
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams{
		HTTPClient: client,
	}
}

/*PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams contains all the parameters to send to the API endpoint
for the put customers customer fid subscriptions subscription fid pre renew operation typically these are written to a http.Request
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams struct {

	/*CustomerFid
	  Customer FID to use

	*/
	CustomerFid string
	/*PriceFid
	  Price FID

	*/
	PriceFid string
	/*SubscriptionFid
	  Subscription FID to use

	*/
	SubscriptionFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) WithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) WithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) WithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) WithCustomerFid(customerFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithPriceFid adds the priceFid to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) WithPriceFid(priceFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	o.SetPriceFid(priceFid)
	return o
}

// SetPriceFid adds the priceFid to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) SetPriceFid(priceFid string) {
	o.PriceFid = priceFid
}

// WithSubscriptionFid adds the subscriptionFid to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) WithSubscriptionFid(subscriptionFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams {
	o.SetSubscriptionFid(subscriptionFid)
	return o
}

// SetSubscriptionFid adds the subscriptionFid to the put customers customer fid subscriptions subscription fid pre renew params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) SetSubscriptionFid(subscriptionFid string) {
	o.SubscriptionFid = subscriptionFid
}

// WriteToRequest writes these params to a swagger request
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidPreRenewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	// form param priceFid
	frPriceFid := o.PriceFid
	fPriceFid := frPriceFid
	if fPriceFid != "" {
		if err := r.SetFormParam("priceFid", fPriceFid); err != nil {
			return err
		}
	}

	// path param subscriptionFid
	if err := r.SetPathParam("subscriptionFid", o.SubscriptionFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
