// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutCustomersCustomerFidLinkVisitorParams creates a new PutCustomersCustomerFidLinkVisitorParams object
// with the default values initialized.
func NewPutCustomersCustomerFidLinkVisitorParams() *PutCustomersCustomerFidLinkVisitorParams {
	var ()
	return &PutCustomersCustomerFidLinkVisitorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCustomersCustomerFidLinkVisitorParamsWithTimeout creates a new PutCustomersCustomerFidLinkVisitorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCustomersCustomerFidLinkVisitorParamsWithTimeout(timeout time.Duration) *PutCustomersCustomerFidLinkVisitorParams {
	var ()
	return &PutCustomersCustomerFidLinkVisitorParams{

		timeout: timeout,
	}
}

// NewPutCustomersCustomerFidLinkVisitorParamsWithContext creates a new PutCustomersCustomerFidLinkVisitorParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCustomersCustomerFidLinkVisitorParamsWithContext(ctx context.Context) *PutCustomersCustomerFidLinkVisitorParams {
	var ()
	return &PutCustomersCustomerFidLinkVisitorParams{

		Context: ctx,
	}
}

// NewPutCustomersCustomerFidLinkVisitorParamsWithHTTPClient creates a new PutCustomersCustomerFidLinkVisitorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCustomersCustomerFidLinkVisitorParamsWithHTTPClient(client *http.Client) *PutCustomersCustomerFidLinkVisitorParams {
	var ()
	return &PutCustomersCustomerFidLinkVisitorParams{
		HTTPClient: client,
	}
}

/*PutCustomersCustomerFidLinkVisitorParams contains all the parameters to send to the API endpoint
for the put customers customer fid link visitor operation typically these are written to a http.Request
*/
type PutCustomersCustomerFidLinkVisitorParams struct {

	/*CustomerFid
	  Customer FID to use

	*/
	CustomerFid string
	/*VisitorID
	  Visitors Id

	*/
	VisitorID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) WithTimeout(timeout time.Duration) *PutCustomersCustomerFidLinkVisitorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) WithContext(ctx context.Context) *PutCustomersCustomerFidLinkVisitorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) WithHTTPClient(client *http.Client) *PutCustomersCustomerFidLinkVisitorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) WithCustomerFid(customerFid string) *PutCustomersCustomerFidLinkVisitorParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithVisitorID adds the visitorID to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) WithVisitorID(visitorID string) *PutCustomersCustomerFidLinkVisitorParams {
	o.SetVisitorID(visitorID)
	return o
}

// SetVisitorID adds the visitorId to the put customers customer fid link visitor params
func (o *PutCustomersCustomerFidLinkVisitorParams) SetVisitorID(visitorID string) {
	o.VisitorID = visitorID
}

// WriteToRequest writes these params to a swagger request
func (o *PutCustomersCustomerFidLinkVisitorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	// form param visitorId
	frVisitorID := o.VisitorID
	fVisitorID := frVisitorID
	if fVisitorID != "" {
		if err := r.SetFormParam("visitorId", fVisitorID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
