// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams() *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParamsWithTimeout creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams object
// with the ability to set a timeout on a request.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParamsWithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams{
		timeout: timeout,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParamsWithContext creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams object
// with the ability to set a context for a request.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParamsWithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams{
		Context: ctx,
	}
}

// NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParamsWithHTTPClient creates a new PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParamsWithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	return &PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams{
		HTTPClient: client,
	}
}

/*
PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams contains all the parameters to send to the API endpoint

	for the put customers customer fid subscriptions subscription fid modify operation.

	Typically these are written to a http.Request.
*/
type PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams struct {

	/* CustomerFid.

	   Customer FID to use
	*/
	CustomerFid string

	// Payload.
	Payload *models.ModifySubscriptionPayload

	/* SubscriptionFid.

	   Subscription FID to use
	*/
	SubscriptionFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put customers customer fid subscriptions subscription fid modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) WithDefaults() *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put customers customer fid subscriptions subscription fid modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) WithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) WithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) WithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) WithCustomerFid(customerFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithPayload adds the payload to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) WithPayload(payload *models.ModifySubscriptionPayload) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) SetPayload(payload *models.ModifySubscriptionPayload) {
	o.Payload = payload
}

// WithSubscriptionFid adds the subscriptionFid to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) WithSubscriptionFid(subscriptionFid string) *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams {
	o.SetSubscriptionFid(subscriptionFid)
	return o
}

// SetSubscriptionFid adds the subscriptionFid to the put customers customer fid subscriptions subscription fid modify params
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) SetSubscriptionFid(subscriptionFid string) {
	o.SubscriptionFid = subscriptionFid
}

// WriteToRequest writes these params to a swagger request
func (o *PutCustomersCustomerFidSubscriptionsSubscriptionFidModifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	// path param subscriptionFid
	if err := r.SetPathParam("subscriptionFid", o.SubscriptionFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
