// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// NewPutCustomersCustomerFidSubscriptionTypeParams creates a new PutCustomersCustomerFidSubscriptionTypeParams object
// with the default values initialized.
func NewPutCustomersCustomerFidSubscriptionTypeParams() *PutCustomersCustomerFidSubscriptionTypeParams {
	var ()
	return &PutCustomersCustomerFidSubscriptionTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCustomersCustomerFidSubscriptionTypeParamsWithTimeout creates a new PutCustomersCustomerFidSubscriptionTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCustomersCustomerFidSubscriptionTypeParamsWithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionTypeParams {
	var ()
	return &PutCustomersCustomerFidSubscriptionTypeParams{

		timeout: timeout,
	}
}

// NewPutCustomersCustomerFidSubscriptionTypeParamsWithContext creates a new PutCustomersCustomerFidSubscriptionTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCustomersCustomerFidSubscriptionTypeParamsWithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionTypeParams {
	var ()
	return &PutCustomersCustomerFidSubscriptionTypeParams{

		Context: ctx,
	}
}

// NewPutCustomersCustomerFidSubscriptionTypeParamsWithHTTPClient creates a new PutCustomersCustomerFidSubscriptionTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCustomersCustomerFidSubscriptionTypeParamsWithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionTypeParams {
	var ()
	return &PutCustomersCustomerFidSubscriptionTypeParams{
		HTTPClient: client,
	}
}

/*PutCustomersCustomerFidSubscriptionTypeParams contains all the parameters to send to the API endpoint
for the put customers customer fid subscription type operation typically these are written to a http.Request
*/
type PutCustomersCustomerFidSubscriptionTypeParams struct {

	/*CustomerFid
	  Customer FID to use

	*/
	CustomerFid string
	/*Payload*/
	Payload *models.SetSubscriptionTypePayload

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) WithTimeout(timeout time.Duration) *PutCustomersCustomerFidSubscriptionTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) WithContext(ctx context.Context) *PutCustomersCustomerFidSubscriptionTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) WithHTTPClient(client *http.Client) *PutCustomersCustomerFidSubscriptionTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerFid adds the customerFid to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) WithCustomerFid(customerFid string) *PutCustomersCustomerFidSubscriptionTypeParams {
	o.SetCustomerFid(customerFid)
	return o
}

// SetCustomerFid adds the customerFid to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) SetCustomerFid(customerFid string) {
	o.CustomerFid = customerFid
}

// WithPayload adds the payload to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) WithPayload(payload *models.SetSubscriptionTypePayload) *PutCustomersCustomerFidSubscriptionTypeParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the put customers customer fid subscription type params
func (o *PutCustomersCustomerFidSubscriptionTypeParams) SetPayload(payload *models.SetSubscriptionTypePayload) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *PutCustomersCustomerFidSubscriptionTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerFid
	if err := r.SetPathParam("customerFid", o.CustomerFid); err != nil {
		return err
	}

	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
