// Code generated by go-swagger; DO NOT EDIT.

package service_status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetServicesServiceFidIncidentsIncidentFidUpdatesReader is a Reader for the GetServicesServiceFidIncidentsIncidentFidUpdates structure.
type GetServicesServiceFidIncidentsIncidentFidUpdatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServicesServiceFidIncidentsIncidentFidUpdatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetServicesServiceFidIncidentsIncidentFidUpdatesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetServicesServiceFidIncidentsIncidentFidUpdatesOK creates a GetServicesServiceFidIncidentsIncidentFidUpdatesOK with default headers values
func NewGetServicesServiceFidIncidentsIncidentFidUpdatesOK() *GetServicesServiceFidIncidentsIncidentFidUpdatesOK {
	return &GetServicesServiceFidIncidentsIncidentFidUpdatesOK{}
}

/*GetServicesServiceFidIncidentsIncidentFidUpdatesOK handles this case with default header values.

Service incidents
*/
type GetServicesServiceFidIncidentsIncidentFidUpdatesOK struct {
	Payload *GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody
}

func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesOK) Error() string {
	return fmt.Sprintf("[GET /services/{serviceFid}/incidents/{incidentFid}/updates][%d] getServicesServiceFidIncidentsIncidentFidUpdatesOK  %+v", 200, o.Payload)
}

func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesOK) GetPayload() *GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody {
	return o.Payload
}

func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServicesServiceFidIncidentsIncidentFidUpdatesDefault creates a GetServicesServiceFidIncidentsIncidentFidUpdatesDefault with default headers values
func NewGetServicesServiceFidIncidentsIncidentFidUpdatesDefault(code int) *GetServicesServiceFidIncidentsIncidentFidUpdatesDefault {
	return &GetServicesServiceFidIncidentsIncidentFidUpdatesDefault{
		_statusCode: code,
	}
}

/*GetServicesServiceFidIncidentsIncidentFidUpdatesDefault handles this case with default header values.

Error
*/
type GetServicesServiceFidIncidentsIncidentFidUpdatesDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the get services service fid incidents incident fid updates default response
func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesDefault) Code() int {
	return o._statusCode
}

func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesDefault) Error() string {
	return fmt.Sprintf("[GET /services/{serviceFid}/incidents/{incidentFid}/updates][%d] GetServicesServiceFidIncidentsIncidentFidUpdates default  %+v", o._statusCode, o.Payload)
}

func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody get services service fid incidents incident fid updates o k body
swagger:model GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody
*/
type GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody struct {
	models.Envelope

	// data
	Data *models.IncidentUpdates `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody) UnmarshalJSON(raw []byte) error {
	// GetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO0
	var getServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO0

	// GetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1
	var dataGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1 struct {
		Data *models.IncidentUpdates `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO0)
	var dataGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1 struct {
		Data *models.IncidentUpdates `json:"data,omitempty"`
	}

	dataGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1.Data = o.Data

	jsonDataGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1, errGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1 := swag.WriteJSON(dataGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1)
	if errGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1 != nil {
		return nil, errGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetServicesServiceFidIncidentsIncidentFidUpdatesOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get services service fid incidents incident fid updates o k body
func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getServicesServiceFidIncidentsIncidentFidUpdatesOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody) UnmarshalBinary(b []byte) error {
	var res GetServicesServiceFidIncidentsIncidentFidUpdatesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
