// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProductsProductFidSkusParams creates a new GetProductsProductFidSkusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProductsProductFidSkusParams() *GetProductsProductFidSkusParams {
	return &GetProductsProductFidSkusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsProductFidSkusParamsWithTimeout creates a new GetProductsProductFidSkusParams object
// with the ability to set a timeout on a request.
func NewGetProductsProductFidSkusParamsWithTimeout(timeout time.Duration) *GetProductsProductFidSkusParams {
	return &GetProductsProductFidSkusParams{
		timeout: timeout,
	}
}

// NewGetProductsProductFidSkusParamsWithContext creates a new GetProductsProductFidSkusParams object
// with the ability to set a context for a request.
func NewGetProductsProductFidSkusParamsWithContext(ctx context.Context) *GetProductsProductFidSkusParams {
	return &GetProductsProductFidSkusParams{
		Context: ctx,
	}
}

// NewGetProductsProductFidSkusParamsWithHTTPClient creates a new GetProductsProductFidSkusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProductsProductFidSkusParamsWithHTTPClient(client *http.Client) *GetProductsProductFidSkusParams {
	return &GetProductsProductFidSkusParams{
		HTTPClient: client,
	}
}

/* GetProductsProductFidSkusParams contains all the parameters to send to the API endpoint
   for the get products product fid skus operation.

   Typically these are written to a http.Request.
*/
type GetProductsProductFidSkusParams struct {

	// ProductFid.
	ProductFid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get products product fid skus params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProductsProductFidSkusParams) WithDefaults() *GetProductsProductFidSkusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get products product fid skus params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProductsProductFidSkusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get products product fid skus params
func (o *GetProductsProductFidSkusParams) WithTimeout(timeout time.Duration) *GetProductsProductFidSkusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get products product fid skus params
func (o *GetProductsProductFidSkusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get products product fid skus params
func (o *GetProductsProductFidSkusParams) WithContext(ctx context.Context) *GetProductsProductFidSkusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get products product fid skus params
func (o *GetProductsProductFidSkusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get products product fid skus params
func (o *GetProductsProductFidSkusParams) WithHTTPClient(client *http.Client) *GetProductsProductFidSkusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get products product fid skus params
func (o *GetProductsProductFidSkusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProductFid adds the productFid to the get products product fid skus params
func (o *GetProductsProductFidSkusParams) WithProductFid(productFid string) *GetProductsProductFidSkusParams {
	o.SetProductFid(productFid)
	return o
}

// SetProductFid adds the productFid to the get products product fid skus params
func (o *GetProductsProductFidSkusParams) SetProductFid(productFid string) {
	o.ProductFid = productFid
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsProductFidSkusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param productFid
	if err := r.SetPathParam("productFid", o.ProductFid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
