// Code generated by go-swagger; DO NOT EDIT.

package reasons

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/fortifi/go-api/models"
)

// GetReasonsGroupsReader is a Reader for the GetReasonsGroups structure.
type GetReasonsGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReasonsGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetReasonsGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetReasonsGroupsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetReasonsGroupsOK creates a GetReasonsGroupsOK with default headers values
func NewGetReasonsGroupsOK() *GetReasonsGroupsOK {
	return &GetReasonsGroupsOK{}
}

/*GetReasonsGroupsOK handles this case with default header values.

Reason groups
*/
type GetReasonsGroupsOK struct {
	Payload *models.GetReasonsGroupsOKBody
}

func (o *GetReasonsGroupsOK) Error() string {
	return fmt.Sprintf("[GET /reasons/groups][%d] getReasonsGroupsOK  %+v", 200, o.Payload)
}

func (o *GetReasonsGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetReasonsGroupsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReasonsGroupsDefault creates a GetReasonsGroupsDefault with default headers values
func NewGetReasonsGroupsDefault(code int) *GetReasonsGroupsDefault {
	return &GetReasonsGroupsDefault{
		_statusCode: code,
	}
}

/*GetReasonsGroupsDefault handles this case with default header values.

Error
*/
type GetReasonsGroupsDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the get reasons groups default response
func (o *GetReasonsGroupsDefault) Code() int {
	return o._statusCode
}

func (o *GetReasonsGroupsDefault) Error() string {
	return fmt.Sprintf("[GET /reasons/groups][%d] GetReasonsGroups default  %+v", o._statusCode, o.Payload)
}

func (o *GetReasonsGroupsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
