// Code generated by go-swagger; DO NOT EDIT.

package entities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetEntitiesEntityFidConfigSectionNameReader is a Reader for the GetEntitiesEntityFidConfigSectionName structure.
type GetEntitiesEntityFidConfigSectionNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEntitiesEntityFidConfigSectionNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEntitiesEntityFidConfigSectionNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetEntitiesEntityFidConfigSectionNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetEntitiesEntityFidConfigSectionNameOK creates a GetEntitiesEntityFidConfigSectionNameOK with default headers values
func NewGetEntitiesEntityFidConfigSectionNameOK() *GetEntitiesEntityFidConfigSectionNameOK {
	return &GetEntitiesEntityFidConfigSectionNameOK{}
}

/*
GetEntitiesEntityFidConfigSectionNameOK describes a response with status code 200, with default header values.

List Of Config Items
*/
type GetEntitiesEntityFidConfigSectionNameOK struct {
	Payload *GetEntitiesEntityFidConfigSectionNameOKBody
}

// IsSuccess returns true when this get entities entity fid config section name o k response has a 2xx status code
func (o *GetEntitiesEntityFidConfigSectionNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get entities entity fid config section name o k response has a 3xx status code
func (o *GetEntitiesEntityFidConfigSectionNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get entities entity fid config section name o k response has a 4xx status code
func (o *GetEntitiesEntityFidConfigSectionNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get entities entity fid config section name o k response has a 5xx status code
func (o *GetEntitiesEntityFidConfigSectionNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get entities entity fid config section name o k response a status code equal to that given
func (o *GetEntitiesEntityFidConfigSectionNameOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetEntitiesEntityFidConfigSectionNameOK) Error() string {
	return fmt.Sprintf("[GET /entities/{entityFid}/config/{sectionName}][%d] getEntitiesEntityFidConfigSectionNameOK  %+v", 200, o.Payload)
}

func (o *GetEntitiesEntityFidConfigSectionNameOK) String() string {
	return fmt.Sprintf("[GET /entities/{entityFid}/config/{sectionName}][%d] getEntitiesEntityFidConfigSectionNameOK  %+v", 200, o.Payload)
}

func (o *GetEntitiesEntityFidConfigSectionNameOK) GetPayload() *GetEntitiesEntityFidConfigSectionNameOKBody {
	return o.Payload
}

func (o *GetEntitiesEntityFidConfigSectionNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetEntitiesEntityFidConfigSectionNameOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEntitiesEntityFidConfigSectionNameDefault creates a GetEntitiesEntityFidConfigSectionNameDefault with default headers values
func NewGetEntitiesEntityFidConfigSectionNameDefault(code int) *GetEntitiesEntityFidConfigSectionNameDefault {
	return &GetEntitiesEntityFidConfigSectionNameDefault{
		_statusCode: code,
	}
}

/*
GetEntitiesEntityFidConfigSectionNameDefault describes a response with status code -1, with default header values.

Error
*/
type GetEntitiesEntityFidConfigSectionNameDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the get entities entity fid config section name default response
func (o *GetEntitiesEntityFidConfigSectionNameDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get entities entity fid config section name default response has a 2xx status code
func (o *GetEntitiesEntityFidConfigSectionNameDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get entities entity fid config section name default response has a 3xx status code
func (o *GetEntitiesEntityFidConfigSectionNameDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get entities entity fid config section name default response has a 4xx status code
func (o *GetEntitiesEntityFidConfigSectionNameDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get entities entity fid config section name default response has a 5xx status code
func (o *GetEntitiesEntityFidConfigSectionNameDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get entities entity fid config section name default response a status code equal to that given
func (o *GetEntitiesEntityFidConfigSectionNameDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetEntitiesEntityFidConfigSectionNameDefault) Error() string {
	return fmt.Sprintf("[GET /entities/{entityFid}/config/{sectionName}][%d] GetEntitiesEntityFidConfigSectionName default  %+v", o._statusCode, o.Payload)
}

func (o *GetEntitiesEntityFidConfigSectionNameDefault) String() string {
	return fmt.Sprintf("[GET /entities/{entityFid}/config/{sectionName}][%d] GetEntitiesEntityFidConfigSectionName default  %+v", o._statusCode, o.Payload)
}

func (o *GetEntitiesEntityFidConfigSectionNameDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetEntitiesEntityFidConfigSectionNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetEntitiesEntityFidConfigSectionNameOKBody get entities entity fid config section name o k body
swagger:model GetEntitiesEntityFidConfigSectionNameOKBody
*/
type GetEntitiesEntityFidConfigSectionNameOKBody struct {
	models.Envelope

	// data
	Data *models.ConfigItems `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetEntitiesEntityFidConfigSectionNameOKBody) UnmarshalJSON(raw []byte) error {
	// GetEntitiesEntityFidConfigSectionNameOKBodyAO0
	var getEntitiesEntityFidConfigSectionNameOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getEntitiesEntityFidConfigSectionNameOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getEntitiesEntityFidConfigSectionNameOKBodyAO0

	// GetEntitiesEntityFidConfigSectionNameOKBodyAO1
	var dataGetEntitiesEntityFidConfigSectionNameOKBodyAO1 struct {
		Data *models.ConfigItems `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetEntitiesEntityFidConfigSectionNameOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetEntitiesEntityFidConfigSectionNameOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetEntitiesEntityFidConfigSectionNameOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getEntitiesEntityFidConfigSectionNameOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getEntitiesEntityFidConfigSectionNameOKBodyAO0)
	var dataGetEntitiesEntityFidConfigSectionNameOKBodyAO1 struct {
		Data *models.ConfigItems `json:"data,omitempty"`
	}

	dataGetEntitiesEntityFidConfigSectionNameOKBodyAO1.Data = o.Data

	jsonDataGetEntitiesEntityFidConfigSectionNameOKBodyAO1, errGetEntitiesEntityFidConfigSectionNameOKBodyAO1 := swag.WriteJSON(dataGetEntitiesEntityFidConfigSectionNameOKBodyAO1)
	if errGetEntitiesEntityFidConfigSectionNameOKBodyAO1 != nil {
		return nil, errGetEntitiesEntityFidConfigSectionNameOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetEntitiesEntityFidConfigSectionNameOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get entities entity fid config section name o k body
func (o *GetEntitiesEntityFidConfigSectionNameOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetEntitiesEntityFidConfigSectionNameOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getEntitiesEntityFidConfigSectionNameOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getEntitiesEntityFidConfigSectionNameOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get entities entity fid config section name o k body based on the context it is used
func (o *GetEntitiesEntityFidConfigSectionNameOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetEntitiesEntityFidConfigSectionNameOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getEntitiesEntityFidConfigSectionNameOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getEntitiesEntityFidConfigSectionNameOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetEntitiesEntityFidConfigSectionNameOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetEntitiesEntityFidConfigSectionNameOKBody) UnmarshalBinary(b []byte) error {
	var res GetEntitiesEntityFidConfigSectionNameOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
