// Code generated by go-swagger; DO NOT EDIT.

package entities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// NewPutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams creates a new PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams() *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	return &PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParamsWithTimeout creates a new PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams object
// with the ability to set a timeout on a request.
func NewPutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParamsWithTimeout(timeout time.Duration) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	return &PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams{
		timeout: timeout,
	}
}

// NewPutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParamsWithContext creates a new PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams object
// with the ability to set a context for a request.
func NewPutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParamsWithContext(ctx context.Context) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	return &PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams{
		Context: ctx,
	}
}

// NewPutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParamsWithHTTPClient creates a new PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParamsWithHTTPClient(client *http.Client) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	return &PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams{
		HTTPClient: client,
	}
}

/*
PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams contains all the parameters to send to the API endpoint

	for the put entities entity fid properties counters property name increment operation.

	Typically these are written to a http.Request.
*/
type PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams struct {

	/* EntityFid.

	   Entity FID to use
	*/
	EntityFid string

	// Payload.
	Payload *models.PropertyCounterPayload

	/* PropertyName.

	   Property Name
	*/
	PropertyName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put entities entity fid properties counters property name increment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) WithDefaults() *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put entities entity fid properties counters property name increment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) WithTimeout(timeout time.Duration) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) WithContext(ctx context.Context) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) WithHTTPClient(client *http.Client) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEntityFid adds the entityFid to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) WithEntityFid(entityFid string) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	o.SetEntityFid(entityFid)
	return o
}

// SetEntityFid adds the entityFid to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) SetEntityFid(entityFid string) {
	o.EntityFid = entityFid
}

// WithPayload adds the payload to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) WithPayload(payload *models.PropertyCounterPayload) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) SetPayload(payload *models.PropertyCounterPayload) {
	o.Payload = payload
}

// WithPropertyName adds the propertyName to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) WithPropertyName(propertyName string) *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams {
	o.SetPropertyName(propertyName)
	return o
}

// SetPropertyName adds the propertyName to the put entities entity fid properties counters property name increment params
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) SetPropertyName(propertyName string) {
	o.PropertyName = propertyName
}

// WriteToRequest writes these params to a swagger request
func (o *PutEntitiesEntityFidPropertiesCountersPropertyNameIncrementParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param entityFid
	if err := r.SetPathParam("entityFid", o.EntityFid); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	// path param propertyName
	if err := r.SetPathParam("propertyName", o.PropertyName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
