// Code generated by go-swagger; DO NOT EDIT.

package entities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PutEntitiesEntityFidLabelsAssignReader is a Reader for the PutEntitiesEntityFidLabelsAssign structure.
type PutEntitiesEntityFidLabelsAssignReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutEntitiesEntityFidLabelsAssignReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutEntitiesEntityFidLabelsAssignOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutEntitiesEntityFidLabelsAssignDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutEntitiesEntityFidLabelsAssignOK creates a PutEntitiesEntityFidLabelsAssignOK with default headers values
func NewPutEntitiesEntityFidLabelsAssignOK() *PutEntitiesEntityFidLabelsAssignOK {
	return &PutEntitiesEntityFidLabelsAssignOK{}
}

/*
PutEntitiesEntityFidLabelsAssignOK describes a response with status code 200, with default header values.

Properties Saved
*/
type PutEntitiesEntityFidLabelsAssignOK struct {
}

// IsSuccess returns true when this put entities entity fid labels assign o k response has a 2xx status code
func (o *PutEntitiesEntityFidLabelsAssignOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put entities entity fid labels assign o k response has a 3xx status code
func (o *PutEntitiesEntityFidLabelsAssignOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put entities entity fid labels assign o k response has a 4xx status code
func (o *PutEntitiesEntityFidLabelsAssignOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put entities entity fid labels assign o k response has a 5xx status code
func (o *PutEntitiesEntityFidLabelsAssignOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put entities entity fid labels assign o k response a status code equal to that given
func (o *PutEntitiesEntityFidLabelsAssignOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put entities entity fid labels assign o k response
func (o *PutEntitiesEntityFidLabelsAssignOK) Code() int {
	return 200
}

func (o *PutEntitiesEntityFidLabelsAssignOK) Error() string {
	return fmt.Sprintf("[PUT /entities/{entityFid}/labels/assign][%d] putEntitiesEntityFidLabelsAssignOK ", 200)
}

func (o *PutEntitiesEntityFidLabelsAssignOK) String() string {
	return fmt.Sprintf("[PUT /entities/{entityFid}/labels/assign][%d] putEntitiesEntityFidLabelsAssignOK ", 200)
}

func (o *PutEntitiesEntityFidLabelsAssignOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutEntitiesEntityFidLabelsAssignDefault creates a PutEntitiesEntityFidLabelsAssignDefault with default headers values
func NewPutEntitiesEntityFidLabelsAssignDefault(code int) *PutEntitiesEntityFidLabelsAssignDefault {
	return &PutEntitiesEntityFidLabelsAssignDefault{
		_statusCode: code,
	}
}

/*
PutEntitiesEntityFidLabelsAssignDefault describes a response with status code -1, with default header values.

Error
*/
type PutEntitiesEntityFidLabelsAssignDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this put entities entity fid labels assign default response has a 2xx status code
func (o *PutEntitiesEntityFidLabelsAssignDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put entities entity fid labels assign default response has a 3xx status code
func (o *PutEntitiesEntityFidLabelsAssignDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put entities entity fid labels assign default response has a 4xx status code
func (o *PutEntitiesEntityFidLabelsAssignDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put entities entity fid labels assign default response has a 5xx status code
func (o *PutEntitiesEntityFidLabelsAssignDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put entities entity fid labels assign default response a status code equal to that given
func (o *PutEntitiesEntityFidLabelsAssignDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put entities entity fid labels assign default response
func (o *PutEntitiesEntityFidLabelsAssignDefault) Code() int {
	return o._statusCode
}

func (o *PutEntitiesEntityFidLabelsAssignDefault) Error() string {
	return fmt.Sprintf("[PUT /entities/{entityFid}/labels/assign][%d] PutEntitiesEntityFidLabelsAssign default  %+v", o._statusCode, o.Payload)
}

func (o *PutEntitiesEntityFidLabelsAssignDefault) String() string {
	return fmt.Sprintf("[PUT /entities/{entityFid}/labels/assign][%d] PutEntitiesEntityFidLabelsAssign default  %+v", o._statusCode, o.Payload)
}

func (o *PutEntitiesEntityFidLabelsAssignDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PutEntitiesEntityFidLabelsAssignDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
