// Code generated by go-swagger; DO NOT EDIT.

package marketing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// DeletePublishersPublisherFidApprovedReader is a Reader for the DeletePublishersPublisherFidApproved structure.
type DeletePublishersPublisherFidApprovedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePublishersPublisherFidApprovedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePublishersPublisherFidApprovedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeletePublishersPublisherFidApprovedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePublishersPublisherFidApprovedOK creates a DeletePublishersPublisherFidApprovedOK with default headers values
func NewDeletePublishersPublisherFidApprovedOK() *DeletePublishersPublisherFidApprovedOK {
	return &DeletePublishersPublisherFidApprovedOK{}
}

/*DeletePublishersPublisherFidApprovedOK handles this case with default header values.

Publisher no longer approved
*/
type DeletePublishersPublisherFidApprovedOK struct {
}

func (o *DeletePublishersPublisherFidApprovedOK) Error() string {
	return fmt.Sprintf("[DELETE /publishers/{publisherFid}/approved][%d] deletePublishersPublisherFidApprovedOK ", 200)
}

func (o *DeletePublishersPublisherFidApprovedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePublishersPublisherFidApprovedDefault creates a DeletePublishersPublisherFidApprovedDefault with default headers values
func NewDeletePublishersPublisherFidApprovedDefault(code int) *DeletePublishersPublisherFidApprovedDefault {
	return &DeletePublishersPublisherFidApprovedDefault{
		_statusCode: code,
	}
}

/*DeletePublishersPublisherFidApprovedDefault handles this case with default header values.

Error
*/
type DeletePublishersPublisherFidApprovedDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the delete publishers publisher fid approved default response
func (o *DeletePublishersPublisherFidApprovedDefault) Code() int {
	return o._statusCode
}

func (o *DeletePublishersPublisherFidApprovedDefault) Error() string {
	return fmt.Sprintf("[DELETE /publishers/{publisherFid}/approved][%d] DeletePublishersPublisherFidApproved default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePublishersPublisherFidApprovedDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *DeletePublishersPublisherFidApprovedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
