// Code generated by go-swagger; DO NOT EDIT.

package marketing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PostAdvertisersAdvertiserFidCampaignsReader is a Reader for the PostAdvertisersAdvertiserFidCampaigns structure.
type PostAdvertisersAdvertiserFidCampaignsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAdvertisersAdvertiserFidCampaignsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAdvertisersAdvertiserFidCampaignsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostAdvertisersAdvertiserFidCampaignsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostAdvertisersAdvertiserFidCampaignsOK creates a PostAdvertisersAdvertiserFidCampaignsOK with default headers values
func NewPostAdvertisersAdvertiserFidCampaignsOK() *PostAdvertisersAdvertiserFidCampaignsOK {
	return &PostAdvertisersAdvertiserFidCampaignsOK{}
}

/*PostAdvertisersAdvertiserFidCampaignsOK handles this case with default header values.

Campaign Created
*/
type PostAdvertisersAdvertiserFidCampaignsOK struct {
	Payload *models.PostAdvertisersAdvertiserFidCampaignsOKBody
}

func (o *PostAdvertisersAdvertiserFidCampaignsOK) Error() string {
	return fmt.Sprintf("[POST /advertisers/{advertiserFid}/campaigns][%d] postAdvertisersAdvertiserFidCampaignsOK  %+v", 200, o.Payload)
}

func (o *PostAdvertisersAdvertiserFidCampaignsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostAdvertisersAdvertiserFidCampaignsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAdvertisersAdvertiserFidCampaignsDefault creates a PostAdvertisersAdvertiserFidCampaignsDefault with default headers values
func NewPostAdvertisersAdvertiserFidCampaignsDefault(code int) *PostAdvertisersAdvertiserFidCampaignsDefault {
	return &PostAdvertisersAdvertiserFidCampaignsDefault{
		_statusCode: code,
	}
}

/*PostAdvertisersAdvertiserFidCampaignsDefault handles this case with default header values.

Error
*/
type PostAdvertisersAdvertiserFidCampaignsDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the post advertisers advertiser fid campaigns default response
func (o *PostAdvertisersAdvertiserFidCampaignsDefault) Code() int {
	return o._statusCode
}

func (o *PostAdvertisersAdvertiserFidCampaignsDefault) Error() string {
	return fmt.Sprintf("[POST /advertisers/{advertiserFid}/campaigns][%d] PostAdvertisersAdvertiserFidCampaigns default  %+v", o._statusCode, o.Payload)
}

func (o *PostAdvertisersAdvertiserFidCampaignsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
