// Code generated by go-swagger; DO NOT EDIT.

package marketing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PutPublishersPublisherFidEnableReader is a Reader for the PutPublishersPublisherFidEnable structure.
type PutPublishersPublisherFidEnableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPublishersPublisherFidEnableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutPublishersPublisherFidEnableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutPublishersPublisherFidEnableDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutPublishersPublisherFidEnableOK creates a PutPublishersPublisherFidEnableOK with default headers values
func NewPutPublishersPublisherFidEnableOK() *PutPublishersPublisherFidEnableOK {
	return &PutPublishersPublisherFidEnableOK{}
}

/*
PutPublishersPublisherFidEnableOK describes a response with status code 200, with default header values.

Publisher enabled
*/
type PutPublishersPublisherFidEnableOK struct {
}

// IsSuccess returns true when this put publishers publisher fid enable o k response has a 2xx status code
func (o *PutPublishersPublisherFidEnableOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put publishers publisher fid enable o k response has a 3xx status code
func (o *PutPublishersPublisherFidEnableOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put publishers publisher fid enable o k response has a 4xx status code
func (o *PutPublishersPublisherFidEnableOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put publishers publisher fid enable o k response has a 5xx status code
func (o *PutPublishersPublisherFidEnableOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put publishers publisher fid enable o k response a status code equal to that given
func (o *PutPublishersPublisherFidEnableOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put publishers publisher fid enable o k response
func (o *PutPublishersPublisherFidEnableOK) Code() int {
	return 200
}

func (o *PutPublishersPublisherFidEnableOK) Error() string {
	return fmt.Sprintf("[PUT /publishers/{publisherFid}/enable][%d] putPublishersPublisherFidEnableOK ", 200)
}

func (o *PutPublishersPublisherFidEnableOK) String() string {
	return fmt.Sprintf("[PUT /publishers/{publisherFid}/enable][%d] putPublishersPublisherFidEnableOK ", 200)
}

func (o *PutPublishersPublisherFidEnableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutPublishersPublisherFidEnableDefault creates a PutPublishersPublisherFidEnableDefault with default headers values
func NewPutPublishersPublisherFidEnableDefault(code int) *PutPublishersPublisherFidEnableDefault {
	return &PutPublishersPublisherFidEnableDefault{
		_statusCode: code,
	}
}

/*
PutPublishersPublisherFidEnableDefault describes a response with status code -1, with default header values.

Error
*/
type PutPublishersPublisherFidEnableDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this put publishers publisher fid enable default response has a 2xx status code
func (o *PutPublishersPublisherFidEnableDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put publishers publisher fid enable default response has a 3xx status code
func (o *PutPublishersPublisherFidEnableDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put publishers publisher fid enable default response has a 4xx status code
func (o *PutPublishersPublisherFidEnableDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put publishers publisher fid enable default response has a 5xx status code
func (o *PutPublishersPublisherFidEnableDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put publishers publisher fid enable default response a status code equal to that given
func (o *PutPublishersPublisherFidEnableDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put publishers publisher fid enable default response
func (o *PutPublishersPublisherFidEnableDefault) Code() int {
	return o._statusCode
}

func (o *PutPublishersPublisherFidEnableDefault) Error() string {
	return fmt.Sprintf("[PUT /publishers/{publisherFid}/enable][%d] PutPublishersPublisherFidEnable default  %+v", o._statusCode, o.Payload)
}

func (o *PutPublishersPublisherFidEnableDefault) String() string {
	return fmt.Sprintf("[PUT /publishers/{publisherFid}/enable][%d] PutPublishersPublisherFidEnable default  %+v", o._statusCode, o.Payload)
}

func (o *PutPublishersPublisherFidEnableDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PutPublishersPublisherFidEnableDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
