// Code generated by go-swagger; DO NOT EDIT.

package marketing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PutPublishersPublisherFidApprovedReader is a Reader for the PutPublishersPublisherFidApproved structure.
type PutPublishersPublisherFidApprovedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPublishersPublisherFidApprovedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutPublishersPublisherFidApprovedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutPublishersPublisherFidApprovedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutPublishersPublisherFidApprovedOK creates a PutPublishersPublisherFidApprovedOK with default headers values
func NewPutPublishersPublisherFidApprovedOK() *PutPublishersPublisherFidApprovedOK {
	return &PutPublishersPublisherFidApprovedOK{}
}

/*PutPublishersPublisherFidApprovedOK handles this case with default header values.

Approved Publisher
*/
type PutPublishersPublisherFidApprovedOK struct {
}

func (o *PutPublishersPublisherFidApprovedOK) Error() string {
	return fmt.Sprintf("[PUT /publishers/{publisherFid}/approved][%d] putPublishersPublisherFidApprovedOK ", 200)
}

func (o *PutPublishersPublisherFidApprovedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutPublishersPublisherFidApprovedDefault creates a PutPublishersPublisherFidApprovedDefault with default headers values
func NewPutPublishersPublisherFidApprovedDefault(code int) *PutPublishersPublisherFidApprovedDefault {
	return &PutPublishersPublisherFidApprovedDefault{
		_statusCode: code,
	}
}

/*PutPublishersPublisherFidApprovedDefault handles this case with default header values.

Error
*/
type PutPublishersPublisherFidApprovedDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the put publishers publisher fid approved default response
func (o *PutPublishersPublisherFidApprovedDefault) Code() int {
	return o._statusCode
}

func (o *PutPublishersPublisherFidApprovedDefault) Error() string {
	return fmt.Sprintf("[PUT /publishers/{publisherFid}/approved][%d] PutPublishersPublisherFidApproved default  %+v", o._statusCode, o.Payload)
}

func (o *PutPublishersPublisherFidApprovedDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PutPublishersPublisherFidApprovedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
