// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// GetOrdersOrderFidReader is a Reader for the GetOrdersOrderFid structure.
type GetOrdersOrderFidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrdersOrderFidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOrdersOrderFidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetOrdersOrderFidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrdersOrderFidOK creates a GetOrdersOrderFidOK with default headers values
func NewGetOrdersOrderFidOK() *GetOrdersOrderFidOK {
	return &GetOrdersOrderFidOK{}
}

/*GetOrdersOrderFidOK handles this case with default header values.

Order retrieved
*/
type GetOrdersOrderFidOK struct {
	Payload *models.Order
}

func (o *GetOrdersOrderFidOK) Error() string {
	return fmt.Sprintf("[GET /orders/{orderFid}][%d] getOrdersOrderFidOK  %+v", 200, o.Payload)
}

func (o *GetOrdersOrderFidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Order)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrdersOrderFidNotFound creates a GetOrdersOrderFidNotFound with default headers values
func NewGetOrdersOrderFidNotFound() *GetOrdersOrderFidNotFound {
	return &GetOrdersOrderFidNotFound{}
}

/*GetOrdersOrderFidNotFound handles this case with default header values.

Order not found
*/
type GetOrdersOrderFidNotFound struct {
}

func (o *GetOrdersOrderFidNotFound) Error() string {
	return fmt.Sprintf("[GET /orders/{orderFid}][%d] getOrdersOrderFidNotFound ", 404)
}

func (o *GetOrdersOrderFidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
