// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PutOrdersOrderFidCancelReader is a Reader for the PutOrdersOrderFidCancel structure.
type PutOrdersOrderFidCancelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutOrdersOrderFidCancelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutOrdersOrderFidCancelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutOrdersOrderFidCancelOK creates a PutOrdersOrderFidCancelOK with default headers values
func NewPutOrdersOrderFidCancelOK() *PutOrdersOrderFidCancelOK {
	return &PutOrdersOrderFidCancelOK{}
}

/*PutOrdersOrderFidCancelOK handles this case with default header values.

Order cancelled
*/
type PutOrdersOrderFidCancelOK struct {
	Payload *models.PutOrdersOrderFidCancelOKBody
}

func (o *PutOrdersOrderFidCancelOK) Error() string {
	return fmt.Sprintf("[PUT /orders/{orderFid}/cancel][%d] putOrdersOrderFidCancelOK  %+v", 200, o.Payload)
}

func (o *PutOrdersOrderFidCancelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PutOrdersOrderFidCancelOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
