// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fortifi/go-api/models"
)

// PutOrdersOrderFidConfirmPayPalReader is a Reader for the PutOrdersOrderFidConfirmPayPal structure.
type PutOrdersOrderFidConfirmPayPalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutOrdersOrderFidConfirmPayPalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutOrdersOrderFidConfirmPayPalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 503:
		result := NewPutOrdersOrderFidConfirmPayPalServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutOrdersOrderFidConfirmPayPalOK creates a PutOrdersOrderFidConfirmPayPalOK with default headers values
func NewPutOrdersOrderFidConfirmPayPalOK() *PutOrdersOrderFidConfirmPayPalOK {
	return &PutOrdersOrderFidConfirmPayPalOK{}
}

/*PutOrdersOrderFidConfirmPayPalOK handles this case with default header values.

Order confirmed and payment authroized
*/
type PutOrdersOrderFidConfirmPayPalOK struct {
	Payload *models.OrderConfirmation
}

func (o *PutOrdersOrderFidConfirmPayPalOK) Error() string {
	return fmt.Sprintf("[PUT /orders/{orderFid}/confirmPayPal][%d] putOrdersOrderFidConfirmPayPalOK  %+v", 200, o.Payload)
}

func (o *PutOrdersOrderFidConfirmPayPalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrderConfirmation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutOrdersOrderFidConfirmPayPalServiceUnavailable creates a PutOrdersOrderFidConfirmPayPalServiceUnavailable with default headers values
func NewPutOrdersOrderFidConfirmPayPalServiceUnavailable() *PutOrdersOrderFidConfirmPayPalServiceUnavailable {
	return &PutOrdersOrderFidConfirmPayPalServiceUnavailable{}
}

/*PutOrdersOrderFidConfirmPayPalServiceUnavailable handles this case with default header values.

There are no payment gateways available to handle your request
*/
type PutOrdersOrderFidConfirmPayPalServiceUnavailable struct {
}

func (o *PutOrdersOrderFidConfirmPayPalServiceUnavailable) Error() string {
	return fmt.Sprintf("[PUT /orders/{orderFid}/confirmPayPal][%d] putOrdersOrderFidConfirmPayPalServiceUnavailable ", 503)
}

func (o *PutOrdersOrderFidConfirmPayPalServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
