// Code generated by go-swagger; DO NOT EDIT.

package payment_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// GetConfigurationFinanceGatewaysReader is a Reader for the GetConfigurationFinanceGateways structure.
type GetConfigurationFinanceGatewaysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigurationFinanceGatewaysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConfigurationFinanceGatewaysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetConfigurationFinanceGatewaysDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetConfigurationFinanceGatewaysOK creates a GetConfigurationFinanceGatewaysOK with default headers values
func NewGetConfigurationFinanceGatewaysOK() *GetConfigurationFinanceGatewaysOK {
	return &GetConfigurationFinanceGatewaysOK{}
}

/*GetConfigurationFinanceGatewaysOK handles this case with default header values.

List of payment gateways
*/
type GetConfigurationFinanceGatewaysOK struct {
	Payload *GetConfigurationFinanceGatewaysOKBody
}

func (o *GetConfigurationFinanceGatewaysOK) Error() string {
	return fmt.Sprintf("[GET /configuration/finance/gateways][%d] getConfigurationFinanceGatewaysOK  %+v", 200, o.Payload)
}

func (o *GetConfigurationFinanceGatewaysOK) GetPayload() *GetConfigurationFinanceGatewaysOKBody {
	return o.Payload
}

func (o *GetConfigurationFinanceGatewaysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetConfigurationFinanceGatewaysOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfigurationFinanceGatewaysDefault creates a GetConfigurationFinanceGatewaysDefault with default headers values
func NewGetConfigurationFinanceGatewaysDefault(code int) *GetConfigurationFinanceGatewaysDefault {
	return &GetConfigurationFinanceGatewaysDefault{
		_statusCode: code,
	}
}

/*GetConfigurationFinanceGatewaysDefault handles this case with default header values.

Error
*/
type GetConfigurationFinanceGatewaysDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// Code gets the status code for the get configuration finance gateways default response
func (o *GetConfigurationFinanceGatewaysDefault) Code() int {
	return o._statusCode
}

func (o *GetConfigurationFinanceGatewaysDefault) Error() string {
	return fmt.Sprintf("[GET /configuration/finance/gateways][%d] GetConfigurationFinanceGateways default  %+v", o._statusCode, o.Payload)
}

func (o *GetConfigurationFinanceGatewaysDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *GetConfigurationFinanceGatewaysDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetConfigurationFinanceGatewaysOKBody get configuration finance gateways o k body
swagger:model GetConfigurationFinanceGatewaysOKBody
*/
type GetConfigurationFinanceGatewaysOKBody struct {
	models.Envelope

	// data
	Data *models.PaymentGateways `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetConfigurationFinanceGatewaysOKBody) UnmarshalJSON(raw []byte) error {
	// GetConfigurationFinanceGatewaysOKBodyAO0
	var getConfigurationFinanceGatewaysOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &getConfigurationFinanceGatewaysOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = getConfigurationFinanceGatewaysOKBodyAO0

	// GetConfigurationFinanceGatewaysOKBodyAO1
	var dataGetConfigurationFinanceGatewaysOKBodyAO1 struct {
		Data *models.PaymentGateways `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetConfigurationFinanceGatewaysOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetConfigurationFinanceGatewaysOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetConfigurationFinanceGatewaysOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getConfigurationFinanceGatewaysOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getConfigurationFinanceGatewaysOKBodyAO0)
	var dataGetConfigurationFinanceGatewaysOKBodyAO1 struct {
		Data *models.PaymentGateways `json:"data,omitempty"`
	}

	dataGetConfigurationFinanceGatewaysOKBodyAO1.Data = o.Data

	jsonDataGetConfigurationFinanceGatewaysOKBodyAO1, errGetConfigurationFinanceGatewaysOKBodyAO1 := swag.WriteJSON(dataGetConfigurationFinanceGatewaysOKBodyAO1)
	if errGetConfigurationFinanceGatewaysOKBodyAO1 != nil {
		return nil, errGetConfigurationFinanceGatewaysOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetConfigurationFinanceGatewaysOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get configuration finance gateways o k body
func (o *GetConfigurationFinanceGatewaysOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConfigurationFinanceGatewaysOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getConfigurationFinanceGatewaysOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetConfigurationFinanceGatewaysOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetConfigurationFinanceGatewaysOKBody) UnmarshalBinary(b []byte) error {
	var res GetConfigurationFinanceGatewaysOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
