// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fortifi/go-api/models"
)

// PostCustomersCustomerFidPaymentMethodsCreatePendingReader is a Reader for the PostCustomersCustomerFidPaymentMethodsCreatePending structure.
type PostCustomersCustomerFidPaymentMethodsCreatePendingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostCustomersCustomerFidPaymentMethodsCreatePendingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostCustomersCustomerFidPaymentMethodsCreatePendingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCustomersCustomerFidPaymentMethodsCreatePendingOK creates a PostCustomersCustomerFidPaymentMethodsCreatePendingOK with default headers values
func NewPostCustomersCustomerFidPaymentMethodsCreatePendingOK() *PostCustomersCustomerFidPaymentMethodsCreatePendingOK {
	return &PostCustomersCustomerFidPaymentMethodsCreatePendingOK{}
}

/*
PostCustomersCustomerFidPaymentMethodsCreatePendingOK describes a response with status code 200, with default header values.

Pending Payment Method Created
*/
type PostCustomersCustomerFidPaymentMethodsCreatePendingOK struct {
	Payload *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody
}

// IsSuccess returns true when this post customers customer fid payment methods create pending o k response has a 2xx status code
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post customers customer fid payment methods create pending o k response has a 3xx status code
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers customer fid payment methods create pending o k response has a 4xx status code
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers customer fid payment methods create pending o k response has a 5xx status code
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers customer fid payment methods create pending o k response a status code equal to that given
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post customers customer fid payment methods create pending o k response
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) Code() int {
	return 200
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) Error() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/paymentMethods/createPending][%d] postCustomersCustomerFidPaymentMethodsCreatePendingOK  %+v", 200, o.Payload)
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) String() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/paymentMethods/createPending][%d] postCustomersCustomerFidPaymentMethodsCreatePendingOK  %+v", 200, o.Payload)
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) GetPayload() *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody {
	return o.Payload
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCustomersCustomerFidPaymentMethodsCreatePendingDefault creates a PostCustomersCustomerFidPaymentMethodsCreatePendingDefault with default headers values
func NewPostCustomersCustomerFidPaymentMethodsCreatePendingDefault(code int) *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault {
	return &PostCustomersCustomerFidPaymentMethodsCreatePendingDefault{
		_statusCode: code,
	}
}

/*
PostCustomersCustomerFidPaymentMethodsCreatePendingDefault describes a response with status code -1, with default header values.

Error
*/
type PostCustomersCustomerFidPaymentMethodsCreatePendingDefault struct {
	_statusCode int

	Payload *models.Envelope
}

// IsSuccess returns true when this post customers customer fid payment methods create pending default response has a 2xx status code
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post customers customer fid payment methods create pending default response has a 3xx status code
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post customers customer fid payment methods create pending default response has a 4xx status code
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post customers customer fid payment methods create pending default response has a 5xx status code
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post customers customer fid payment methods create pending default response a status code equal to that given
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post customers customer fid payment methods create pending default response
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) Code() int {
	return o._statusCode
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) Error() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/paymentMethods/createPending][%d] PostCustomersCustomerFidPaymentMethodsCreatePending default  %+v", o._statusCode, o.Payload)
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) String() string {
	return fmt.Sprintf("[POST /customers/{customerFid}/paymentMethods/createPending][%d] PostCustomersCustomerFidPaymentMethodsCreatePending default  %+v", o._statusCode, o.Payload)
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) GetPayload() *models.Envelope {
	return o.Payload
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Envelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody post customers customer fid payment methods create pending o k body
swagger:model PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody
*/
type PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody struct {
	models.Envelope

	// data
	Data *models.Fid `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody) UnmarshalJSON(raw []byte) error {
	// PostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO0
	var postCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO0 models.Envelope
	if err := swag.ReadJSON(raw, &postCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO0); err != nil {
		return err
	}
	o.Envelope = postCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO0

	// PostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1
	var dataPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1 struct {
		Data *models.Fid `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	postCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO0, err := swag.WriteJSON(o.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO0)
	var dataPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1 struct {
		Data *models.Fid `json:"data,omitempty"`
	}

	dataPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1.Data = o.Data

	jsonDataPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1, errPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1 := swag.WriteJSON(dataPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1)
	if errPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1 != nil {
		return nil, errPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1
	}
	_parts = append(_parts, jsonDataPostCustomersCustomerFidPaymentMethodsCreatePendingOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post customers customer fid payment methods create pending o k body
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postCustomersCustomerFidPaymentMethodsCreatePendingOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postCustomersCustomerFidPaymentMethodsCreatePendingOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post customers customer fid payment methods create pending o k body based on the context it is used
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Envelope
	if err := o.Envelope.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postCustomersCustomerFidPaymentMethodsCreatePendingOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postCustomersCustomerFidPaymentMethodsCreatePendingOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody) UnmarshalBinary(b []byte) error {
	var res PostCustomersCustomerFidPaymentMethodsCreatePendingOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
