// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActionCancelFlowPayload Generic Response
//
// swagger:model ActionCancelFlowPayload
type ActionCancelFlowPayload struct {
	ActionableCancelFlowPayload

	// decision key
	DecisionKey string `json:"decisionKey,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ActionCancelFlowPayload) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ActionableCancelFlowPayload
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ActionableCancelFlowPayload = aO0

	// AO1
	var dataAO1 struct {
		DecisionKey string `json:"decisionKey,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.DecisionKey = dataAO1.DecisionKey

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ActionCancelFlowPayload) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.ActionableCancelFlowPayload)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		DecisionKey string `json:"decisionKey,omitempty"`
	}

	dataAO1.DecisionKey = m.DecisionKey

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this action cancel flow payload
func (m *ActionCancelFlowPayload) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ActionableCancelFlowPayload
	if err := m.ActionableCancelFlowPayload.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this action cancel flow payload based on the context it is used
func (m *ActionCancelFlowPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ActionableCancelFlowPayload
	if err := m.ActionableCancelFlowPayload.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ActionCancelFlowPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionCancelFlowPayload) UnmarshalBinary(b []byte) error {
	var res ActionCancelFlowPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
