// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ActionableCancelFlowPayload actionable cancel flow payload
//
// swagger:model ActionableCancelFlowPayload
type ActionableCancelFlowPayload struct {

	// existing flow fid
	ExistingFlowFid string `json:"existingFlowFid,omitempty"`

	// ip
	IP string `json:"ip,omitempty"`

	// Time in ISO 8601 standard with optional fractions of a second e.g 2015-12-05T13:11:59.888Z
	// Format: date-time
	Time strfmt.DateTime `json:"time,omitempty"`

	// user agent
	UserAgent string `json:"userAgent,omitempty"`

	// user fid
	UserFid string `json:"userFid,omitempty"`
}

// Validate validates this actionable cancel flow payload
func (m *ActionableCancelFlowPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActionableCancelFlowPayload) validateTime(formats strfmt.Registry) error {
	if swag.IsZero(m.Time) { // not required
		return nil
	}

	if err := validate.FormatOf("time", "body", "date-time", m.Time.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this actionable cancel flow payload based on context it is used
func (m *ActionableCancelFlowPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionableCancelFlowPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionableCancelFlowPayload) UnmarshalBinary(b []byte) error {
	var res ActionableCancelFlowPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
