// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AdvertiserCampaignAllOf1 advertiser campaign all of1
// swagger:model advertiserCampaignAllOf1
type AdvertiserCampaignAllOf1 struct {

	// affiliate fid
	AffiliateFid string `json:"affiliateFid,omitempty"`

	// brand fid
	BrandFid string `json:"brandFid,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`
}

// Validate validates this advertiser campaign all of1
func (m *AdvertiserCampaignAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AdvertiserCampaignAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdvertiserCampaignAllOf1) UnmarshalBinary(b []byte) error {
	var res AdvertiserCampaignAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
