// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// BrandFid FID of a valid Brand
// swagger:model brandFid
type BrandFid string

// Validate validates this brand fid
func (m BrandFid) Validate(formats strfmt.Registry) error {
	return nil
}
