// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// CardAddressCity City for the card
// swagger:model cardAddressCity
type CardAddressCity string

// Validate validates this card address city
func (m CardAddressCity) Validate(formats strfmt.Registry) error {
	return nil
}
