// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// FirstName First Name
// swagger:model firstName
type FirstName string

// Validate validates this first name
func (m FirstName) Validate(formats strfmt.Registry) error {
	return nil
}
