// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImportCost Import Publisher Cost Response
//
// swagger:model ImportCost
type ImportCost struct {

	// fid
	Fid string `json:"fid,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// result
	Result bool `json:"result,omitempty"`
}

// Validate validates this import cost
func (m *ImportCost) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this import cost based on context it is used
func (m *ImportCost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImportCost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImportCost) UnmarshalBinary(b []byte) error {
	var res ImportCost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
