// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InvoiceItemAllOf1 invoice item all of1
// swagger:model invoiceItemAllOf1
type InvoiceItemAllOf1 struct {

	// sub items
	SubItems []*InvoiceSubItem `json:"subItems"`

	// total amount
	TotalAmount float32 `json:"totalAmount,omitempty"`
}

// Validate validates this invoice item all of1
func (m *InvoiceItemAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InvoiceItemAllOf1) validateSubItems(formats strfmt.Registry) error {

	if swag.IsZero(m.SubItems) { // not required
		return nil
	}

	for i := 0; i < len(m.SubItems); i++ {
		if swag.IsZero(m.SubItems[i]) { // not required
			continue
		}

		if m.SubItems[i] != nil {
			if err := m.SubItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("subItems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InvoiceItemAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvoiceItemAllOf1) UnmarshalBinary(b []byte) error {
	var res InvoiceItemAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
