// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InvoiceDownloadResponse Generic Response
// swagger:model InvoiceDownloadResponse
type InvoiceDownloadResponse struct {

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this invoice download response
func (m *InvoiceDownloadResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InvoiceDownloadResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvoiceDownloadResponse) UnmarshalBinary(b []byte) error {
	var res InvoiceDownloadResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
