// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// PhoneNumber Phone Number
// swagger:model phoneNumber
type PhoneNumber string

// Validate validates this phone number
func (m PhoneNumber) Validate(formats strfmt.Registry) error {
	return nil
}
