// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PutOrdersOrderFidConfirmPayPalOKBody put orders order fid confirm pay pal o k body
// swagger:model putOrdersOrderFidConfirmPayPalOKBody
type PutOrdersOrderFidConfirmPayPalOKBody struct {
	Envelope

	PutOrdersOrderFidConfirmPayPalOKBodyAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PutOrdersOrderFidConfirmPayPalOKBody) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Envelope
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Envelope = aO0

	// AO1
	var aO1 PutOrdersOrderFidConfirmPayPalOKBodyAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.PutOrdersOrderFidConfirmPayPalOKBodyAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PutOrdersOrderFidConfirmPayPalOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Envelope)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.PutOrdersOrderFidConfirmPayPalOKBodyAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this put orders order fid confirm pay pal o k body
func (m *PutOrdersOrderFidConfirmPayPalOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Envelope
	if err := m.Envelope.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with PutOrdersOrderFidConfirmPayPalOKBodyAllOf1
	if err := m.PutOrdersOrderFidConfirmPayPalOKBodyAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PutOrdersOrderFidConfirmPayPalOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PutOrdersOrderFidConfirmPayPalOKBody) UnmarshalBinary(b []byte) error {
	var res PutOrdersOrderFidConfirmPayPalOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
