// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ServiceIncidentsPayload service incidents payload
// swagger:model ServiceIncidentsPayload
type ServiceIncidentsPayload struct {

	// end date
	EndDate strfmt.DateTime `json:"endDate,omitempty"`

	// start date
	StartDate strfmt.DateTime `json:"startDate,omitempty"`
}

// Validate validates this service incidents payload
func (m *ServiceIncidentsPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceIncidentsPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceIncidentsPayload) UnmarshalBinary(b []byte) error {
	var res ServiceIncidentsPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
