// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Sid2 Advertised sub tracking ID 2
// swagger:model sid2
type Sid2 string

// Validate validates this sid2
func (m Sid2) Validate(formats strfmt.Registry) error {
	return nil
}
